### PR TITLE
1.x: Add Completable.doOnCompleted and deprecate Completable.doOnComplete

### LINKED ISSUE #3700: Make Observable.doOnCompleted name match Completable.doOnComplete in 1.x
`Observable` has a `doOnCompleted` method (past tense), and `Completable` has `doOnComplete` (present tense). The 2.x branch changes `Observable`'s method to be present tense. The 1.x branch can add alias the past tense method in `Observable` and deprecate it.

I'm happy to make the change if this is approved.

### PR DESCRIPTION
**Pull request by zach-klippenstein**
Closes #3700.

### CODE REVIEW

**Comment by akarnokd** [comment]
Wait, what? I thought you wanted to add `Completable.doOnCompleted()`. I see no reason to change the established naming of `Observable.doOnCompleted()`. In fact, for consistency, I'd rather prefer adding `Completable.doOnCompleted`.

**Comment by zach-klippenstein** [comment]
That makes sense. The only reason I did it this way is because on the 2.x branch both [Observable](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Observable.java#L1714) and [Completable](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Completable.java#L1230) use `doOnComplete()`.

**Comment by akarnokd** [comment]
Yes, those follow the reactive-streams convention and Completable started out as a 2.x addition. In the meantime, I'll fix that test failure.

**Comment by zach-klippenstein** [comment]
Changed `Completable` instead, updated tests to match.

**Comment by akarnokd** [comment]
:+1:

**Comment by zsxwing** [comment]
@zach-klippenstein Thanks! Just updated the title. :+1:

**Comment by stevegury** [comment]
:+1:

**Pull request merged**
