### PR TITLE
1.x: Completable class to support valueless event composition + tests

### PR DESCRIPTION
**Pull request by akarnokd**
This is a backport of #3439.

### CODE REVIEW

**Comment by stealthcode** [comment]
Looks good. Should we annotate `@Experimental` on all the public methods and operators?

**Comment by akarnokd** [comment]
Now, the class annotation should indicate all methods are experimental. If individual methods get promoted, we can add direct annotations then.

**Comment by stealthcode** [comment]
Sounds good :+1:

**Comment by akarnokd** [comment]
Since this adds to the API surface, I'd like to get another like before merging.

**Comment by stevegury** [comment]
:+1:

**Comment by stealthcode** [comment]
Awesome. Thanks!

**Pull request merged**
