### PR TITLE
use Exceptions.throwOrError to simplify error handling

### PR DESCRIPTION
**Pull request by davidmoten**
This PR simplifies error handling by making use of existing `Exceptions.throwOrError` overloads.

A number of classes are touched by this one PR but I'm assuming review will be easy enough that merge can happen soon.

### CODE REVIEW

**Comment by thomasnield** [comment]
It looks like my optimize imports messed up the imports on `Observable.java`. I'll restore them to what they were originally.

**Comment by akarnokd** [comment]
:+1:

**Comment by thomasnield** [comment]
Oops sorry wrong PR

**Comment by zsxwing** [comment]
:+1:

**Pull request merged**
