### PR TITLE
2.x: Add Checkstyle for Trailing Whitespace

### PR DESCRIPTION
**Pull request by vanniktech**
This will add checkstyle though it should not be executed together with Travis and hence does not fail the PR if there are. Also running `./gradlew checkstyleMain` gives a list of places where trailing whitespace exists.

### CODE REVIEW

**Comment by JakeWharton** [comment]
> it should not be executed together with Travis and hence does not fail the PR

Seems pointless to add then.

**Comment by vanniktech** [comment]
Yeah having the same opinion but David doesn't want it to fail the PR.

**Comment by JakeWharton** [comment]
Then why fail local builds?

**Comment by akarnokd** [comment]
For now, just run it with `./gradlew checkstyleMain` sometimes.

**Comment by akarnokd** [comment]
Yet it does fail it https://travis-ci.org/ReactiveX/RxJava/builds/158395672#L205

**Comment by vanniktech** [comment]
Alright my bad #4505

I thought the checkstyle tasks would not be executed automatically though `build` executes `check` and `checkstyle` task hooked itself into `check` task.

**Pull request merged**
