### PR TITLE
2.x: coverage and cleanup 10/12-1

### PR DESCRIPTION
**Pull request by akarnokd**
- Add coverage to remaining `Completable` operators
- Fix inner Throwable order for `CompletablePeek`
- Compact/rewrite a few operators

### CODE REVIEW

**Comment by vanniktech** [comment]
@akarnokd you missed the wrong CompositeException constructor call in [`CompletableResumeNext`](https://github.com/ReactiveX/RxJava/blob/35c29511c9b3275ad8094289f796fee696298dbe/src/main/java/io/reactivex/internal/operators/completable/CompletableResumeNext.java#L56)

**Review by JakeWharton — APPROVED** [review]

**Comment by akarnokd** [comment]
@vanniktech yeah. Would you like to do a PR?

**Comment by vanniktech** [comment]
I'll include that in one that I was planning to push out anyways today which is a big bigger. ~60 files

**Comment by akarnokd** [comment]
What are you changing in 60 files?

**Comment by vanniktech** [comment]
Null cleanups

**Pull request merged**
