### PR TITLE
2.x: Observable test change dispose to cancel

### PR DESCRIPTION
**Pull request by vanniktech**

### CODE REVIEW

**Comment by vanniktech** [comment]
Oh right cancel does not exist on `TestObserver` yet it should though, right?

**Comment by akarnokd** [comment]
Yes, it should be conditionally disposed. Didn't your IDE warn about the missing method?

**Comment by vanniktech** [comment]
It did but I somehow managed to ignore it and didn't run the tests locally. Should I create the cancel method on `TestObserver` or just leave it as is and close this PR?

**Comment by akarnokd** [comment]
Just use `dispose`.

**Comment by vanniktech** [comment]
Alright then this can be closed.

**Pull request closed without merging**
