### PR TITLE
2.x: Parallelize unit test execution for speed!

### PR DESCRIPTION
**Pull request by JakeWharton**
This gives me a 57% reduction in execution time.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Looks like Travis can't handle it. I can disable it for CI builds where build speed isn't really important.

**Comment by akarnokd** [comment]
This increases the likelihood of timeouts during heavy times. Maybe later.

**Comment by akarnokd** [comment]
In addition, some tests may conflict because they may change the global hooks. I'm guessing there isn't a JUnit annotation that allows some tests to run in parallel with others while forbidding for others?

**Comment by JakeWharton** [comment]
They run in forked JVMs so any static state won't clash.

**Comment by akarnokd** [comment]
Okay, let's try it.

**Pull request merged**
