### PR TITLE
Observable.from(iterable) - ensure it.hasNext() is not called unnecessarily #3006

### PR DESCRIPTION
**Pull request by davidmoten**
This PR is a fix for #3006.

Ensured `it.hasNext()` not called more often than required especially when unsubscription happens before completion.

Added two unit tests (one for fast path and the other for backpressure) that failed on previous codebase.

### CODE REVIEW

**Comment by akarnokd** [comment]
You forgot to implement ````remove()``` which is only default in Java 8.

**Comment by davidmoten** [comment]
Ta, fixed.

**Comment by akarnokd** [comment]
Still it doesn't compile:

/home/travis/build/ReactiveX/RxJava/src/test/java/rx/internal/operators/OnSubscribeFromIterableTest.java:233: error: <anonymous rx.internal.operators.OnSubscribeFromIterableTest$4$1> is not abstract and does not override abstract method remove() in Iterator
                return new Iterator<Integer>() {

**Comment by davidmoten** [comment]
woops, there were two of them. Fixed.

**Comment by zsxwing** [comment]
LGTM :+1:

**Comment by akarnokd** [comment]
Thanks!

**Pull request merged**
