### PR TITLE
Update Mockito to 2.1.0-RC.2

### PR DESCRIPTION
**Pull request by TimvdLippe**
Equivalent of #4634 , but now for the 2.x branch.

### CODE REVIEW

**Comment by TimvdLippe** [comment]
The test `io.reactivex.maybe.MaybeTest > onTerminateDetach` seems to be failing, claiming there is a memory leak. I sadly have no experience with this test to fix it.

**Comment by akarnokd** [comment]
That test is a bit flaky (maybe the new Mockito increased the base memory usage?). I'll fix that test and rerun this one.

**Review by akarnokd — APPROVED** [review]

**Comment by TimvdLippe** [comment]
Thanks a lot and enjoy :smile: !

**Comment by TimvdLippe** [comment]
FYI Mockito 2.1.0 has been released which is equivalent to 2.1.0-RC.2. Once again thanks a lot for using Mockito :smile:

**Pull request merged**
