### PR TITLE
2.x: Rename Single Base Interface Types for consistency

### PR DESCRIPTION
**Pull request by vanniktech**
Addresses #4044

### CODE REVIEW

**Comment by JakeWharton** [comment]
lgtm :+1:

**Comment by akarnokd** [comment]
:+1:

**Comment by vanniktech** [comment]
@JakeWharton if you want me to and you haven't started yet I'd continue on that list and rename the other classes / interfaces as well

**Comment by JakeWharton** [comment]
Sure. Go for it!

**Pull request merged**
