### PR TITLE
Composite exception should update cause to match the correct throwable that's first in the chain

### PR DESCRIPTION
**Pull request by premnirmal**
Fixes https://github.com/ReactiveX/RxJava/issues/3679

### CODE REVIEW

**Comment by akarnokd** [comment]
Please add an unit test that shows verifies the expected behavior.

**Comment by premnirmal** [comment]
Updated

**Comment by zsxwing** [comment]
@premnirmal This is not correct. I just sent #3977 to fix it. Thanks anyway!

**Comment by akarnokd** [comment]
Thanks for the contribution. Could you check #3977 and verify it fixes your issue?

**Comment by premnirmal** [comment]
Thanks @zsxwing , closing

**Pull request closed without merging**
