### PR TITLE
1.x: Gradle Wrapper 2.8, RxJava project plugin 3.0.0

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
// Actually, I am slowly preparing RxJava for running tests on Android during CI.

Netflix team: PTAL, hope you're ok with new rxjava-project plugin.

### CODE REVIEW

**Comment by akarnokd** [comment]
:+1:

**Comment by hzsweers** [comment]
Out of curiosity, what happened to this?

**Comment by artem-zinnatullin** [comment]
Sad story :( 

PR was not merged for 2 months and I decided to close it because Gradle shipped two releases after 2.8. 

Netflix team didn't show any interest. 

I guess Gradle 2.11 will be released sooner than your PR with 2.10 will be merged, though I wish you good luck!

**Comment by hzsweers** [comment]
@akarnokd can you provide any insight?

**Comment by akarnokd** [comment]
See #3659. I use 2.8 without Netflix plugin in my other projects, RxJava breaks from time to time.

**Pull request closed without merging**
