### PR TITLE
1.x: Fix Observable delay methods typos in documenation

### PR DESCRIPTION
**Pull request by neoranga55**

### CODE REVIEW

**Comment by akarnokd** [comment]
Great, thanks!

:+1:

**Comment by artem-zinnatullin** [comment]
:+1:

**Comment by vanniktech** [comment]
@neoranga55 there's also one [here](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/Single.java#L2365)

**Comment by neoranga55** [comment]
@vanniktech do you suggest adding the fix for Single to this current PR or opening a new one?

**Comment by akarnokd** [comment]
Maybe its easier to search for that typo in all files and fix them in a single PR.

**Comment by vanniktech** [comment]
@akarnokd that's exactly what I did `ack compuation` and it returned me the two places he already fixed it and then the other one in Single

**Comment by akarnokd** [comment]
Okay, to be clear, please fix the type on Single as well in this PR.

**Comment by neoranga55** [comment]
Ok, added the fix for Single, I'm not familiar with the branching flow here so I did the one I'm familiar with: rebase to collapse both changes into a single commit.

**Comment by vanniktech** [comment]
Looking good now :+1:

**Comment by akarnokd** [comment]
We prefer single commit PRs so you did right by squashing the commits.

**Comment by stevegury** [comment]
:+1:

**Pull request merged**
