### PR TITLE
Add Completable.andThen(Completable), deprecate endWith()

### LINKED ISSUE #3947: Request: Completable.andThen(Completable)
To match `Completable#andThen(Observable<T> next)` and `Completable#andThen(Single<T> next)` it would be nice if there were an operator like this:

`Completable#andThen(Completable next)`.

Unless there is some other way to achieve the same functionality right now.

### PR DESCRIPTION
**Pull request by vanniktech**
See #3947

### CODE REVIEW

**Comment by akarnokd** [comment]
Please update unit tests that use these deprecated methods.

**Comment by vanniktech** [comment]
Done.

**Comment by akarnokd** [comment]
:+1:

**Comment by artem-zinnatullin** [comment]
👍 but I'd either duplicate tests or make universal test functions and test both `endWith` and `andThen` to make sure that we don't break old behavior of public api.

**Comment by vanniktech** [comment]
The question is also since Completable is still `@Experimental` we could if this is wanted go the hard way and remove the deprecated methods and make everyone force to use the standard (new) methods since there are already quite a few deprecated / duplicated methods.

**Comment by zsxwing** [comment]
👍 

> but I'd either duplicate tests or make universal test functions and test both endWith and andThen to make sure that we don't break old behavior of public api.

@artem-zinnatullin I'm not against it but this is really minor as `andThen` just calls `endWith`. I'm going to merge this. Feel free to add tests in a separate PR if you wish.

**Pull request merged**
