### PR TITLE
Add specificity to documentation for AsyncSubject

### PR DESCRIPTION
**Pull request by DavidDTA**
This documentation answers questions I had while reading it.

### CODE REVIEW

**Comment by akarnokd** [comment]
I'd also add if the source terminated with an `onError` (with or without prior `onNext`s) all current and future `Subscriber`s will receive only the error.

**Comment by akarnokd** [comment]
:+1:

**Comment by DavidDTA** [comment]
What is the protocol from here on out?

**Comment by akarnokd** [comment]
Thanks for the contribution. I'll merge this as is. I'll write up my intentions as a lead developer including cases such as this as an example.

**Comment by DavidMGross** [comment]
There's an additional marble diagram you could add that illustrates this,
if you think that would help:
http://reactivex.io/documentation/operators/images/S.AsyncSubject.e.png

On Fri, Jun 17, 2016 at 12:00 AM, David Karnok notifications@github.com
wrote:

> I'd also add if the source terminated with an onError (with or without
> prior onNexts) all current and future Subscribers will receive only the
> error.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ReactiveX/RxJava/pull/4014#issuecomment-226695444,
> or mute the thread
> https://github.com/notifications/unsubscribe/AESHoCEyPX_KJDrLy48kFDKbxRi3133Kks5qMkX_gaJpZM4I4DMC
> .

## 

David M. Gross
PLP Consulting

**Comment by akarnokd** [comment]
Thanks @DavidMGross ! @hospitalitarian would you like to submit another PR?

**Comment by DavidDTA** [comment]
Yes, I will.  How do you generate marble diagrams?  There are a few more cases that I would like to add.

**Comment by DavidMGross** [comment]
OmniGraffle is the tool we're using to create the diagrams. You can check
out the diagram set from the RxJava wiki here:
https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators.graffle

(Though by ReactiveX/reactivex.github.io#223 this file may get moved over
to that repo at some point as it makes more sense to have it there.)

On Fri, Jun 17, 2016 at 10:02 AM, David Andrews notifications@github.com
wrote:

> Yes, I will. How do you generate marble diagrams? There are a few more
> cases that I would like to add.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/ReactiveX/RxJava/pull/4014#issuecomment-226824595,
> or mute the thread
> https://github.com/notifications/unsubscribe/AESHoEHo26mfko7SMJ_LS_jhChngBIh8ks5qMtM1gaJpZM4I4DMC
> .

## 

David M. Gross
PLP Consulting

**Comment by DavidDTA** [comment]
Should I wait for that file to be moved?  Otherwise, how do I go about
editing the wiki file?

**Comment by DavidMGross** [comment]
I've got other things on my plate, so probably won't be moving the graffle
file soon. You can check it out from the repo at
https://github.com/Netflix/RxJava.wiki.git to make changes. Let me know if
you've got questions about how the file is organized, how to generate .png
images from it and check those in, etc.

On Fri, Jun 17, 2016 at 12:16 PM, David Andrews notifications@github.com
wrote:

> Should I wait for that file to be moved? Otherwise, how do I go about
> editing the wiki file?
> 
> On Fri, Jun 17, 2016 at 3:08 PM, David Gross notifications@github.com
> wrote:
> 
> > OmniGraffle is the tool we're using to create the diagrams. You can check
> > out the diagram set from the RxJava wiki here:
> > 
> > https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators.graffle
> > 
> > (Though by ReactiveX/reactivex.github.io#223 this file may get moved
> > over
> > to that repo at some point as it makes more sense to have it there.)
> > 
> > On Fri, Jun 17, 2016 at 10:02 AM, David Andrews <
> > notifications@github.com>
> > wrote:
> > 
> > > Yes, I will. How do you generate marble diagrams? There are a few more
> > > cases that I would like to add.
> > > 
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/ReactiveX/RxJava/pull/4014#issuecomment-226824595
> > > ,
> > > or mute the thread
> > > <
> > 
> > https://github.com/notifications/unsubscribe/AESHoEHo26mfko7SMJ_LS_jhChngBIh8ks5qMtM1gaJpZM4I4DMC
> > 
> > > .
> > 
> > ## 
> > 
> > David M. Gross
> > PLP Consulting
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/ReactiveX/RxJava/pull/4014#issuecomment-226855431,
> > or mute the thread
> > <
> > https://github.com/notifications/unsubscribe/AA-Ue7U2qdN9jKjpXXsFyTfrTpV_eij1ks5qMvDHgaJpZM4I4DMC
> > 
> > .
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/ReactiveX/RxJava/pull/4014#issuecomment-226857431,
> or mute the thread
> https://github.com/notifications/unsubscribe/AESHoBEmPjKGjWYKYjtxgGPszxdjtdXOks5qMvKSgaJpZM4I4DMC
> .

## 

David M. Gross
PLP Consulting

**Pull request merged**
