### PR TITLE
Update Observable.java

### PR DESCRIPTION
**Pull request by daawa**
Thank you for contributing to RxJava. Before pressing the "Create Pull Request" button, please consider the following points:

  - [x] Please give a description about what and why you are contributing, even if it's trivial.

  - [x] Please include the issue list number(s) or other PR numbers in the description if you are contributing in response to those.

  - [x] Please include a reasonable set of unit tests if you contribute new code or change an existing one. If you contribute an operator, (if applicable) please make sure you have tests for working with an `empty`, `just`, `range` of values as well as an `error` source, with and/or without backpressure and see if unsubscription/cancellation propagates correctly.

change the order of generalized types of Operator to be consistent with Func1

### CODE REVIEW

**Comment by akarnokd** [comment]
Such changes violate the established contract of the `Operator` and breaks everybody.

**Comment by akarnokd** [comment]
Correction: The input of the call is the downstream Subscriber which is usually `R` as **r**esult type. The output of the operator is the upstream Subscriber which is usually `T` for inpu**t**.

**Comment by daawa** [comment]
It doesn't matter what the letters are , just keep in line with Func1 interface where T is input, R is output: 

```
public interface Func1<T, R> extends Function {
    R call(T t);
}
```

**Comment by akarnokd** [comment]
Still no good:

```java
Operator<T, R> extends Func1<Subscriber<? super T>, Subscriber<? super R>>
```

The `Func1` receives the subscriber of downstream which is the output. If the `Operator<T, R>` follows the input-output ordering, the `Func1` should be `Func1<Subscriber<? super R>, Subscribe<? super T>>` which would break everybody.

**Comment by daawa** [comment]
ok ,got it . what you mean by _output_ is the emission of observable right?

**Comment by akarnokd** [comment]
Output is what is is emitted towards the downstream. Input is what is received from upstream.

**Pull request closed without merging**
