### PR TITLE
Operator flat map rewrite

### PR DESCRIPTION
**Pull request by akarnokd**
An alternative to #2928 by using flatMap(o -> o) == merge() identity.

Benchmark:

image

It is slightly better than #2928 for flatMap() benchmarks and slightly worse than merge()

### CODE REVIEW

**Comment by benjchristensen** [comment]
What do the columns represent in that benchmark?

**Comment by akarnokd** [comment]
1.x = current head, 
1st try = rewrite but only with the scalar optimizations, 
3rd try = rewrite+scalar optimizations + unbounded mode optimizations, 
flatMap = merge implemented with flatMap instead the other way around so merge(map(func)) inlines func into merge and saves on a lift() call.

**Comment by davidmoten** [comment]
I made this comment on your tool's site but I think we can't assess whether the benchmarks indicate *significant* change unless the error value is taken into account and I assume these visualizations always ignore the error value (is that right?).

**Comment by akarnokd** [comment]
I'm closing this in favor of the recent changes in #2928.

**Pull request closed without merging**
