### PR TITLE
2.x: Remove conditional resource management from async listeners.

### PR DESCRIPTION
**Pull request by JakeWharton**
Rename them to have a 'Resource' prefix.

### CODE REVIEW

**Comment by JakeWharton** [comment]
The value of and distinction between the 'Resource' listeners, 'Default' listeners, and 'Disposable' listeners seems very low. Do we need all these individual types?

**Comment by akarnokd** [comment]
I believe the minimum we require is the ability to dispose a `Subscriber` because that's expected the most. I don't think associating resources with or allowing async requesting is that common.

**Comment by akarnokd** [comment]
I leave it to you to remove the unnecessary; we can add them back later or better yet, they can live in a separate library.

**Comment by JakeWharton** [comment]
Yeah. I need to write something non-trivial with 2.x first. Maybe I'll try
this weekend. I definitely think we should be aggressive in minimizing API
surface since it's easy to add but impossible to take away after release.

**Comment by akarnokd** [comment]
I have a 2.x "dumping ground" for leftovers: https://github.com/akarnokd/RxJava2Extensions so we don't lose things.

**Pull request merged**
