### PR TITLE
1.x: scan with an initial factory callback

### PR DESCRIPTION
**Pull request by akarnokd**
This PR adds an overload to `scan` which allows specifying an initial value factory. The initial value factory is invoked for each incoming Subscriber individually and provides a non-shared starting point for the `scan` operation.

I propose the `scan(Func2 accumulator, Func0 initialFactory)` parameter order because some Java 8+ compilers can't properly disambiguate with `scan(R initialValue, Func2 accumulator)`, thinking that R can be made `Func0`. 

Related: #3667

### CODE REVIEW

**Comment by abersnaze** [comment]
Why add the overload if it can be done with defer and scan then?

**Comment by akarnokd** [comment]
Yep, it can be done. A decision has to be made if this convenience should make it into the library or not, and notify @NiteshKant the outcome in #3667.

**Comment by davidmoten** [comment]
I'd like to see this overload in, thanks.

**Comment by zsxwing** [comment]
I'm not strong against adding it but not like the idea of the new parameter order. I would give +1 if giving it a better name instead of changing the parameter order. By the way, there is already a `OperatorScan(Func0<R> initialValueFactory, Func2<R, ? super T, R> accumulator)` for this overload so you don't need to use `defer`.

Probably @benjchristensen should take a look since you removed it before.

**Comment by benjchristensen** [comment]
It was removed due to ambiguity as shown in https://github.com/ReactiveX/RxJava/issues/1881#issue-48878398

As long as that issue is not recreated, I have nothing against the functionality pursued here. I too don't like solving the overload ambiguity by moving parameter order around. But there is no good solution, it's either that or a new name.

**Comment by akarnokd** [comment]
As an alternative, I suggest extending `scan`'s javadoc with the example of the defer trick.

**Comment by akarnokd** [comment]
The argument order bothers me as well. I'll close this and post a javadoc update instead.

**Pull request closed without merging**
