### PR TITLE
Remove unnecessary static modifier

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
P.S. 
@benjchristensen @akarnokd sorry for large amount of simple pull requests, I'm doing full code review of RxJava sources http://artemzin.com/blog/rxjava-code-review-part-1/ and I'll create PRs and issues during this review.

I'll try to group changes by themes so it will be easy to review them. Looks like this adventure is going to be part of #3145!

### CODE REVIEW

**Comment by akarnokd** [comment]
If it were only me, I'd accept cosmetic changes such as this, but history tells me not to.

**Comment by artem-zinnatullin** [comment]
@akarnokd why? Sad that `javac` is not strict enough and allows such things. We can add `checkstyle` with only java-lang rules and remove all these things from the code, but last time I suggested to add `checkstyle` @benjchristensen was not very happy…

I understand that RxJava is not "my project" and I can't just come and force you to use "my codestyle" (which is actually just standard java codestyle), so if you don't want to accept such changes — it's okay, I'll stop doing such PRs and will report only major issues.

**Comment by akarnokd** [comment]
I like this PR too much, I'm going to merge it ;)

**Comment by benjchristensen** [comment]
> I like this PR too much, I'm going to merge it ;)

:-)

**Pull request merged**
