### PR TITLE
2.x: flatMap{Completable, Maybe, Single} operators

### PR DESCRIPTION
**Pull request by akarnokd**
This PR adds `Observable.flatMapCompletable(Function<T, CompletableSource>)` and `Flowable.flatMapCompletable(Function<T, CompletableSource>)`, both resulting in `Completable` (+ support for fusing back to the original type).

**Edit**

Added `flatMapMaybe` and `flatMapSingle` variants to both `Flowable` and `Observable`.

### CODE REVIEW

**Comment by akarnokd** [comment]
The build gets killed at the jacocoTestResults:

```
:jacocoTestReportgradle/buildViaTravis.sh: line 16:  2970 Killed                  ./gradlew -Prelease.useLastTag=true build
```

I've rerun it a couple of times. Maybe Travis is overloaded at the moment.

**Comment by akarnokd** [comment]
Updated with the remaining operators.

**Review by JakeWharton — APPROVED** [review]
My brain melted slightly reviewing these operators, but looks good.

**Comment by vanniktech** [comment]
Thanks a lot for taking this one over @akarnokd

**Pull request merged**
