### PR TITLE
2.x: coverage, add SingleToFlowableTest

### PR DESCRIPTION
**Pull request by ggikko**
Add "SingleToFlowableTest" to cover toFlowable with test.

### CODE REVIEW

**Comment by akarnokd** [comment]
The operator is covered 100% already btw: [SingleToFlowable](https://codecov.io/gh/ReactiveX/RxJava/src/2.x/src/main/java/io/reactivex/internal/operators/single/SingleToFlowable.java)

**Comment by akarnokd** [comment]
You could, hovewer, see if the other classes could be covered better: https://codecov.io/gh/ReactiveX/RxJava/tree/2.x/src/main/java/io/reactivex/internal/operators

**Comment by akarnokd** [comment]
My mistake, looked at the complexity column.

**Comment by ggikko** [comment]
well.. I thought it was not covered "if (DisposableHelper.validate(this.d, d))" in SingleToFlowable

I got it. thanks for link.

**Comment by ggikko** [comment]
I have a question. There are many duplicate codes in Test code. How about zip these codes to one method for cleaning.

**Comment by akarnokd** [comment]
You mean `TestHelper`? The types are different and they can't be reasonably factored out.

**Comment by ggikko** [comment]
I see. :)

**Pull request merged**
