### PR TITLE
1.x: Fix Completable swallows OnErrorNotImplementedException

### PR DESCRIPTION
**Pull request by prt2121**
Fixed https://github.com/ReactiveX/RxJava/issues/3860

### CODE REVIEW

**Comment by akarnokd** [comment]
Looks good, :+1:

I wonder, shouldn't we switch to `Exceptions.throwIfFatal` as in `Observable`? Of course, the whole `Completable` needs rechecking.

**Comment by prt2121** [comment]
Thanks for your review. I guess we need another clean-up PR for `Exceptions.throwIfFatal`?

**Comment by prt2121** [comment]
Updated to use `Exceptions.throwIfFatal`. Thanks!

**Comment by zsxwing** [comment]
👍

**Pull request merged**
