### PR TITLE
Making RxPlugins reset() public

### PR DESCRIPTION
**Pull request by shivangshah**
Discussions found here: https://github.com/ReactiveX/RxJava/issues/2297

### CODE REVIEW

**Comment by hzsweers** [comment]
:+1:

**Comment by stevegury** [comment]
Based on the discussion, it's definitely helpful, but also dangerous.
Could you add a comment indicating that it's dangerous?

Otherwise 👍

**Comment by artem-zinnatullin** [comment]
Yeah, same concern about dangerous that this method may add. 

It looks like an easy way to do testing but in multithreaded environment (integrational or functional tests for example) it may break a lot of things in "random" manner.

@stevegury @akarnokd let's also mark it as `@Experimental` so we'll be able to remove it if community will have more issues than benefits?

**Comment by stevegury** [comment]
Yeah, good idea for the `@Experimental` flag

**Comment by shivangshah** [comment]
Thanks for the feedback @stevegury , @artem-zinnatullin. Just added the `@experimental` tag. Comments in the PR + commit message.

**Comment by stevegury** [comment]
Please add a javadoc block, and explicitly mention that resetting the plugins is dangerous/unsafe during application runtime (I suspect most people won't check the link), keep the link at the end.

**Comment by JakeWharton** [comment]
@shivangshah Friendly ping. Please update with Javadoc.

**Comment by shivangshah** [comment]
@JakeWharton yes .. thanks for the reminder this totally slipped my mind .. Let me do it now ..

**Comment by shivangshah** [comment]
@JakeWharton : Done ! Let me know if we need to add anything else as a part of the documentation.

**Comment by akarnokd** [comment]
:+1:

**Comment by stevegury** [comment]
👍

**Pull request merged**
