### PR TITLE
2.x: Flowable.combineLatest combiner should not return null

### PR DESCRIPTION
**Pull request by davidmoten**
As per #5376 the combiner should not return null when applied.

* added unit test that failed on original code 
* mentioned constraint in javadoc

I'll look for some others as well.

### CODE REVIEW

**Comment by davidmoten** [comment]
Hah, I take that back! The unit test did not fail on original code. I'll check this one with @akarnokd because to get test coverage of this one requires fusion.

**Comment by davidmoten** [comment]
More cases in 

* FlowableFlattenIterable, ObservableFlattenIterable (throws NPE but without helpful message),
* FlowableInternalHelper, ObservableInternalHelper
* FlowableWithLatestFromMany
* MaybeFlatMapIterableObserver  (throws NPE but without helpful message),
* MaybeZipArray
* perhaps more, I stopped looking.

I notice there is a `@NonNull` annotation on the `Function` interface so perhaps the javadoc changes are not necessary.   I'll close this PR for the moment to have a more thorough look.

**Comment by akarnokd** [comment]
This particular lack of null check is on the fusion path. I'll compose a PR that fixes it and all the other places I can find.

**Comment by davidmoten** [comment]
Beaut @akarnokd, thanks

**Pull request closed without merging**
