### PR TITLE
Add marble diagrams for Single.repeat operators

### PR DESCRIPTION
**Pull request by UMFsimke**
Here are marbles for `repeat`, `repeat(times)` and `repeatWhen` operator in #5788

Please let me know if I need to change anything on the diagram itself. If not, please send me URL when you upload image within the project so I can change URL for the marble in the PR.

I intentionally added two diagrams for `repeatWhen` as I would say its interesting case that people should be aware of.

**EDIT:**
Here are marbles

`repeat` operator:
repeat

`repeat(count)` operator:
repeat with count

`repeatWhen` operator:
repeatWhen

### CODE REVIEW

**Comment by UMFsimke** [comment]
I see few errors. Timeline for flowables should end with error/complete event and should not continue beyond them. I'll update that tomorrow

**Comment by akarnokd** [comment]
It would be great if you linked the diagrams in the PR text.

**Comment by akarnokd** [comment]
Could you also add shadows to the marbles and X?

**Comment by UMFsimke** [comment]
Updated images and PR comment

**Comment by akarnokd** [comment]
- `https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Single.repeat.png`
- `https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Single.repeat.n.png`
- `https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/Single.repeatWhen.png`

**Comment by UMFsimke** [comment]
Thanks! PR is now updated

**Review by akarnokd — APPROVED** [review]

**Review by vanniktech — APPROVED** [review]

**Pull request merged**
