### PR TITLE
1.x: ignore .pmd file in root directory

### PR DESCRIPTION
**Pull request by akarnokd**
The PMD tool in local IDE tends to create this custom file. Add a rule to ignore it.

### CODE REVIEW

**Comment by vanniktech** [comment]
How about also adding `local.properties`?

**Comment by akarnokd** [comment]
Isn't that Android specific?

**Comment by vanniktech** [comment]
I get it when I'm opening the project via AS so yes could be.

**Comment by akarnokd** [comment]
Sure. I'm merging this so please post a separate PR as I'm into something else right now.

**Pull request merged**
