### PR TITLE
1.x: fix timed replay() replaying old data for late subscribers

### PR DESCRIPTION
**Pull request by akarnokd**
In the current master, `replay` only trucates its buffer if an event is received. This means if a subscriber subscribes between two events, the operator may replay old events. This PR skips those events. The operator is now consistent with the recently updated `ReplaySubject`.

The old behavior was somewhat expected by a few unit tests that have been updated.

Related: #3917, #3918.

### CODE REVIEW

**Comment by stevegury** [comment]
👍 
We should mention this change in the next changelog.

**Comment by akarnokd** [comment]
Definitely. 

@zsxwing Thoughts?

**Comment by zsxwing** [comment]
:+1: Agreed that this is a bug fix instead of a broken change.

**Comment by akarnokd** [comment]
Thanks @zsxwing !

**Pull request merged**
