### PR TITLE
Add marbles for Single.timer, Single.defer and Single.toXXX operators

### PR DESCRIPTION
**Pull request by UMFsimke**
Here are marbles for `defer`, `timer(delay, unit)`, `timer(delay, unit, scheduler)`, `toFlowable`, `toMaybe`, `toFuture` operators in #5788 

Marble for `defer`:
defer

Marble for `timer(delay, unit)`:
timer

Marble for `timer(delay, unit, scheduler)`:
timerScheduler

Marble for `toFuture`, although for this one I believe we should add case when there is no event sent from Single as there will be timeout exception thrown:
toFuture

Marble for `toMaybe`:
toMaybe

Marble for `toFlowable`, although here I didnt figured out what will happen if we request more than 1 event from flowable:
toFlowable

### CODE REVIEW

**Comment by akarnokd** [comment]
defer: I would have drawn it with a curly brace listing the 3 options below each other. Please add the subscribe() indicators as well.

toFuture: I indicate Future<T> with a 6-sided shape and indicate get() call and a return. See Completable.fromFuture for an example.

toFlowable: simply indicate request(N). Any positive N has the same effect with this operator. However, an error is always pushed through even without a request; just remove the request(1) from that side of the diagram.

**Comment by akarnokd** [comment]
@UMFsimke are you still around?

**Comment by UMFsimke** [comment]
Yes. I have in plan to wrap it up today... sorry for delay I was on vacation

**Comment by UMFsimke** [comment]
@akarnokd Are these ok now?

I'm a bit confused by what you exactly had in mind for `defer` and `toFuture`.

Please update me if they are fine as I do need to update image sizes in javadoc.
tofuture
toflowable
defer

**Comment by akarnokd** [comment]
Yes, these are okay.

**Comment by UMFsimke** [comment]
Thanks. Updated javadoc.

**Review by akarnokd — APPROVED** [review]

**Pull request merged**
