### PR TITLE
test/subjects: Use statically imported never() methods

### PR DESCRIPTION
**Pull request by Turbo87**
... and remove the unused Mockito imports

### CODE REVIEW

**Comment by akarnokd** [comment]
See #3291.

**Comment by Turbo87** [comment]
@akarnokd are you seriously suggesting that cleaning up code to make it more consistent is a bad thing and shouldn't be done?

**Comment by akarnokd** [comment]
Cosmetic PRs, especially on unit test or on internal classes, don't really contribute anything to the library.

**Comment by Turbo87** [comment]
wow...

**Comment by benjchristensen** [comment]
I'm okay with this type of change. It makes the code more consistent, and is a simple non-intrusive change.

**Comment by benjchristensen** [comment]
Thank you @Turbo87 for the contribution!

**Comment by Turbo87** [comment]
@benjchristensen cool, thanks!

**Comment by akarnokd** [comment]
@Turbo87 I apologize for my harsh and dry comments. Generally, I'm in favor of cleanups such as yours and would have done it the same way. I was under the false impression that the project doesn't want such cleanups. I'm sorry if I offended you.

**Comment by Turbo87** [comment]
@akarnokd nevermind, seems it all worked out in the end ;)

**Pull request merged**
