### PR TITLE
1.x: ReplaySubject now supports backpressure

### PR DESCRIPTION
**Pull request by akarnokd**
In addition, the behavior of time-limited mode has been changed. Late subscribers will now skip stale data.

Related issue: #3917

### CODE REVIEW

**Comment by hzsweers** [comment]
Would it be possible to split this up into a couple commits? GitHub won't show the diff in its current state and says to view locally

**Comment by akarnokd** [comment]
No, ReplaySubject has simply too many expected features: unbounded, size bounded and size+time bounded modes, each adding 100s of lines. It is fully rewritten so comparison wouldn't do much help.

**Comment by stealthcode** [comment]
This makes it very difficult to review. What do you propose @akarnokd ?

**Comment by akarnokd** [comment]
Check out and have your IDE compare this PR against the master version.

**Comment by stealthcode** [comment]
> Late subscribers will now skip stale data.

Does this mean that subscribers were not skipping stale data? This change sounds fixing a bug?

**Comment by akarnokd** [comment]
In the original, once the source completed, the current elements in the bounded buffers were frozen in time. Late subscribers would get all the data, including those who have become older by the time these subscriptions happen. Same was true for live, but inactive replays where a subscriber would started from an outdated element. These were expected by the unit tests but #3917 expected only fresh data.

**Comment by stevegury** [comment]
👍

**Pull request merged**
