### PR TITLE
Add "since" annotations to javadocs for new Experimental/Beta methods

### PR DESCRIPTION
**Pull request by DavidMGross**

### CODE REVIEW

**Comment by DavidMGross** [comment]
Probably a good time to regenerate and deploy the javadocs too.

**Comment by akarnokd** [comment]
Thanks!

**Comment by akarnokd** [comment]
Can the PLP branch be deleted?

**Comment by DavidMGross** [comment]
yes...

On Thu, Jul 23, 2015 at 6:14 AM, David Karnok <notifications@github.com>
wrote:

> Can the PLP branch be deleted?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxJava/pull/3077#issuecomment-124093228>.
>



-- 
David M. Gross
PLP Consulting

**Pull request merged**
