### PR TITLE
Merge with max concurrency now supports backpressure.

### PR DESCRIPTION
**Pull request by akarnokd**
See #2291

### CODE REVIEW

**Comment by akarnokd** [comment]
I can't be sure, but probably the first Travis CI build timed out because the test used too many threads.

**Comment by benjchristensen** [comment]
Thanks for tackling this. Do you think it's better to keep this separate or to have a single `merge` implementation? I was leaning towards having a single impl since `merge` is so hard to get right, and all the perf and backpressure aspects are needed for both.

**Comment by akarnokd** [comment]
I would have to combine merge, mergeDelayError and mergeMaxConcurrent. Adding error delaying to mmc shouldn't be difficult, but applying the scalar-synchronous-value optimization as well is quite difficult. I'd say let's have them separate for now.

**Comment by benjchristensen** [comment]
Keeping them separate means we'll be doing bug fixes and optimizations separately on each of them, and performance will be misleadingly different for each. I suggest that if we do merge this it is only a short-term thing. 

`mergeDelayError` has already been moved into the `merge` implementation. I did that a while back. So it's just the concurrency limit that needs to be moved.

**Comment by akarnokd** [comment]
It would be great if my other merge PR gets verified so I can base the joint operator on something that's actually working for others.

**Comment by akarnokd** [comment]
I'm merging this for now as combining the two is difficult and I don't want to hold 1.0.5 release back. From then on, a single implementation would be just an internal affair.

**Comment by benjchristensen** [comment]
Agreed.

**Pull request merged**
