### PR TITLE
Removes all anonymous inner classes

### PR DESCRIPTION
**Pull request by SleimanJneidi**
This is a what left to complete [this one](https://github.com/ReactiveX/RxJava/pull/5174) :

  - Removes all AICs

  - Issue [#5150](https://github.com/ReactiveX/RxJava/issues/5150)

### CODE REVIEW

**Comment by naturalwarren** [comment]
@SleimanJneidi what's the motivation behind making this change?

**Comment by SleimanJneidi** [comment]
@naturalwarren to improve stack-traces and to reduce the footprint.

**Comment by naturalwarren** [comment]
> @naturalwarren to improve stack-traces and to reduce the footprint.

Makes sense, thanks for filling me in!

**Review by akarnokd — APPROVED** [review]
Great!

**Pull request merged**
