### PR TITLE
Update the Javadoc of the `retry` operator

### PR DESCRIPTION
**Pull request by RomanWuattier**
Specify that the `times` function parameter describes "the number of times
to resubscribe if the current Observable fails".

Solves: #6402

### CODE REVIEW

**Comment by RomanWuattier** [comment]
Bellow is the marble with the number of retries decreased from 2 to 1. If the marble is correct, can you upload it to the repository?
retry o n

**Comment by akarnokd** [comment]
Sure. Could you also make sure all the other counted `retry()` operators in the other base classes have the correct wording?

**Comment by RomanWuattier** [comment]
Sure.
I updated every base classes. Also, I grabbed this opportunity to update some unit tests to illustrate the Javadoc wording.

Please, note:
* `Single` already has the right wording.
* Both `Maybe` and `Flowable` are using the default `retry` marble (https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/retry.png)

**Review by akarnokd — APPROVED** [review]

**Comment by akarnokd** [comment]
Nice! Thanks!

**Review by vanniktech — APPROVED** [review]

**Pull request merged**
