### PR TITLE
2.x: Disposable already set! using delaySubscription with takeUntil/repeatWhen

### PR DESCRIPTION
**Pull request by eleventigers**
When using a combination of `takeUntil`/`repeatWhen` operators on an `Observable` with `delaySubscription` operator applied, it is possible to encounter a `ProtocolViolationException: Disposable already set!` thrown by `RepeatWhenObserver#onSubscribe`. It appears that if `delaySubscription` uses an `ObservableSource` which rapidly/concurrently emits multiple notifications a rare race condition leads to a double subscription issue. 

I am not sure if this issue is a user error (`take(1)` on `ObservableSource` supplied to `delaySubscription` alleviates it) or a bug in RxJava hence me opening this PR with a slow test case that demonstrates this issue.

### CODE REVIEW

**Comment by akarnokd** [comment]
Thanks for reporting a possible bug, but why haven't you just posted an issue with the unit test that fails? Posting a full PR without an actual resolution is not useful for us maintainers.

**Comment by eleventigers** [comment]
@akarnokd no worries, I will re-open this as an issue.

**Comment by eleventigers** [comment]
Tracking issue: https://github.com/ReactiveX/RxJava/issues/6358

**Comment by vanniktech** [comment]
> Thanks for reporting a possible bug, but why haven't you just posted an issue with the unit test that fails? Posting a full PR without an actual resolution is not useful for us maintainers.

We might want to note that somewhere. Many other repositories/organizations like this.

**Pull request closed without merging**
