### PR TITLE
Dump the graph of subscriptions via toString()

### PR DESCRIPTION
**Pull request by akarnokd**
Example:
```
rx.internal.operators.OperatorMerge$MergeSubscriber[id=0, unsubscribed=false, requested=128] {
    op={
        rx.internal.operators.OperatorScan$2[id=1, unsubscribed=false, requested=-9223372036854775808] {
            op={
                rx.internal.operators.OperatorTakeLast$1[id=2, unsubscribed=false, requested=9223372036854775807] {
                    op={
                        rx.internal.operators.OperatorSingle$1[id=3, unsubscribed=false, requested=-9223372036854775808] {
                            op={
                                rx.observers.SafeSubscriber[id=4, unsubscribed=false, requested=-9223372036854775808] {
                                    op={
                                        rx.observables.BlockingObservable$3[id=5, unsubscribed=false, requested=-9223372036854775808] {
                                            op=null
                                            cs={
                                                rx.internal.util.SubscriptionList[id=6, size=2, unsubscribed=false] {
                                                    rx.subscriptions.BooleanSubscription[id=7, unsubscribed=false, action=rx.internal.operators.OnSubscribeUsing$1@704921a5[id=8]]
                                                    rx.internal.operators.OperatorMerge$MergeSubscriber[id=0] { ... }
                                                }
                                            }
                                            p=rx.internal.operators.TakeLastQueueProducer@df27fae[id=9]]
                                        }
                                    }
                                    cs={
                                        rx.internal.util.SubscriptionList[id=6] { ... }
                                    }
                                    p=rx.internal.operators.TakeLastQueueProducer@df27fae[id=9]]
                                }
                            }
                            cs={
                                rx.internal.util.SubscriptionList[id=6] { ... }
                            }
                            p=rx.internal.operators.TakeLastQueueProducer@df27fae[id=9]]
                        }
                    }
                    cs={
                        rx.internal.util.SubscriptionList[id=6] { ... }
                    }
                    p=rx.internal.operators.OperatorScan$2$1@24a35978[id=10]]
                }
            }
            cs={
                rx.internal.util.SubscriptionList[id=6] { ... }
            }
            p=null
        }
    }
    cs={
        rx.internal.util.SubscriptionList[id=6] { ... }
    }
    p=null
}
```

### CODE REVIEW

**Comment by benjchristensen** [comment]
Interesting. @abersnaze can you please review this since it relates to the type of stuff you've done with debugging?

@akarnokd it is conflicting so can you please rebate it?

**Comment by akarnokd** [comment]
Sure.

**Comment by abersnaze** [comment]
It looks interesting.  I'll play with this to see what it does with things like `flatMap` and `defer`.

**Comment by benjchristensen** [comment]
Any feedback on this @abersnaze?

**Comment by abersnaze** [comment]
It is interesting but has some serious limitations:

* This only gives a snapshot of the observable chain at the time `toString()` is called because it only relays on the `Subscription`s.  For example in the `SerialSubscription` only the current subscription can be dumped without caching all of the previous values or future values are still unknown.

* All of the uses of `Subscriptions.create(Action0)` are opaque. For example groupBy has this subscription that delegates to another but won't show in dump.

```
            child.add(Subscriptions.create(new Action0() {
                public void call() {
                    if (WIP_FOR_UNSUBSCRIBE_UPDATER.decrementAndGet(self) == 0) {
                        self.unsubscribe();
                    }
                }
```

**Comment by akarnokd** [comment]
Closing this as being too old and isn't broad enough.

**Pull request closed without merging**
