### PR TITLE
Improving Javadoc of flattenAsFlowable and flattenAsObservable method

### PR DESCRIPTION
**Pull request by thiyagu-7**
Improving the javadoc of the `flattenAsFlowable` and `flattenAsObservable` methods of `Single` and `Maybe` classes.

Resolves: #6276

### CODE REVIEW

**Review by akarnokd — APPROVED** [review]

**Comment by thiyagu-7** [comment]
@akarnokd The force push only involves changing my email in the previous commit. Apologies for the confusion.. I'm not sure why the build has failed.

>io.reactivex.internal.operators.flowable.FlowableConcatMapTest > boundaryFusionDelayError FAILED
    java.lang.AssertionError: Error(s) present: [io.reactivex.exceptions.MissingBackpressureException: Queue is full?!] (latch = 0, values = 1, errors = 1, completions = 0)
        at io.reactivex.observers.BaseTestConsumer.fail(BaseTestConsumer.java:189)
        at io.reactivex.observers.BaseTestConsumer.assertNoErrors(BaseTestConsumer.java:274)
        at io.reactivex.observers.BaseTestConsumer.assertResult(BaseTestConsumer.java:797)
        at io.reactivex.internal.operators.flowable.FlowableConcatMapTest.boundaryFusionDelayError(FlowableConcatMapTest.java:105)
        Caused by:
        io.reactivex.exceptions.MissingBackpressureException: Queue is full?!

**Comment by thiyagu-7** [comment]
@akarnokd I closed and reopened the PR to enable a rebuild and this time it has passed. Was there any transient known build failures here?

**Review by vanniktech — APPROVED** [review]
Probably a flaky test caused the failure.

**Comment by akarnokd** [comment]
Thanks. That test should be deterministic and not fail, unless there is a bug in concatMap's backpressure management. Did you save the full stacktrace of the failure by any chance?

**Comment by thiyagu-7** [comment]
@akarnokd Actually, that is all I saw as part of the failure.

This was the failing build - https://travis-ci.org/ReactiveX/RxJava/builds/494276690

**Pull request merged**
