### PR TITLE
feat: add support for just operator

### PR DESCRIPTION
**Pull request by BirjuVachhani**
just operator was overloaded to support maximum 10 items

replaced all the overloaded methods with a method which supports varargs so that just operator can take any number of value supported by java varargs, not just 10.

### CODE REVIEW

**Comment by JakeWharton** [comment]
This API already exists:

https://github.com/ReactiveX/RxJava/blob/fd63c492c576a2784a5665925457b75355ecffaa/src/main/java/io/reactivex/Observable.java#L1738

Also you reformatted the entire file making it unreviewable.

**Comment by akarnokd** [comment]
Why, why, why? 

> replaced all the overloaded methods

You practically broke binary compatibility with this which we do not allow. Besides, there is a reason for the 1..10 argument variants' existence, namely to avoid the unchecked conversion warnings due to Java 6 limitations in typical usage cases.

**Comment by BirjuVachhani** [comment]
As far as I know, Binary compatibility will break if the method is not found but I think binary compatibility will not break because the replaced method has the same name as the overloaded methods and it takes varargs as arguments so it can replace all the overloaded method without breaking binary compatibility. 

And I didn't get your second point about unchecked conversion warnings. it would be great if you can explain it.

And why overload it to maximum of 10?

**Comment by akarnokd** [comment]
> binary compatibility will not break because the replaced method has the same name

Wrong. Compatibility requires the same number and types of arguments to remain the same. A varargs argument counts as one argument.

> And I didn't get your second point about unchecked conversion warnings. 

Whenever there is a `method(T... arg)` in Java 6, you'll most likely get a compiler warnings about unchecked conversion. Suggested reading: https://stackoverflow.com/questions/21132692/java-unchecked-unchecked-generic-array-creation-for-varargs-parameter

> And why overload it to maximum of 10?

We had to stop at some number to not bloat the API. You can define static methods on some class of yours which can define more than 10 arguments if you need.

**Comment by BirjuVachhani** [comment]
So if new code is added to the file then the binary compatibility will break or not?

**Comment by akarnokd** [comment]
https://docs.oracle.com/javase/specs/jls/se7/html/jls-13.html

**Comment by BirjuVachhani** [comment]
Thanks for the information. I really appreciate it and it helped to learn new things as well. 👍

**Pull request closed without merging**
