### PR TITLE
1.x: Release 1.1.4 CHANGES.md update

### PR DESCRIPTION
**Pull request by akarnokd**
Release 1.1.4 CHANGES.md update.

:+1: for the release.

### CODE REVIEW

**Comment by zsxwing** [comment]
👍

**Comment by stevegury** [comment]
👍

**Comment by akarnokd** [comment]
Excellent, @stevegury would you do the release?

**Comment by stevegury** [comment]
@akarnokd I've published the release, Travis is currently building/publishing the jars...

**Comment by akarnokd** [comment]
Fantastic!

**Pull request merged**
