### PR TITLE
Add wrapper task and update to gradle 2.10

### PR DESCRIPTION
**Pull request by hzsweers**
Was using a pretty old version of gradle. Tests all run normally for me locally with this

### CODE REVIEW

**Comment by JakeWharton** [comment]
You can rarely update Gradle when you use Netflix's Nebula plugins. They are violently linked to implementation details because reasons.

**Comment by hzsweers** [comment]
Ah, guess that explains why there haven't been any updates lately. Should I close this then?

**Comment by JakeWharton** [comment]
Or step the version backwards until it works. It's a shame since the speed
improvements in 2.4 and 2.9+ are great. For RxAndroid we purged all the
Nebula plugins because they held the project back.

**Comment by hzsweers** [comment]
eesh, yeah not even 2.3 will work. I was misled locally since the `wrapper` task worked the first time, but that made sense since `2.2.1` worked fine. Closing for now then. Wonder what the status is, came across #3501 after digging a bit more and seems it was closed without explanation.

**Pull request closed without merging**
