### PR TITLE
Readme: Cherry-pick fixes from #6683, add ProGuard workaround entry

### PR DESCRIPTION
**Pull request by akarnokd**
- Pick the accepted changes from #6683.
- Add entry about ProGuard and Reactive Streams JAR warning issue.

### CODE REVIEW

**Review by vanniktech — COMMENTED** [review]
Would be nice to embed them https://twitter.com/jakewharton/status/1004401938467876865?lang=en

**Comment by akarnokd** [comment]
If I understand #6698, the issue was disabling R8, which had no problems to begin with, and the default ProGuard complaining. Looks like this embed would work only with R8.

**Comment by vanniktech** [comment]
AFAIK, this only does work for R8 yes. Would still be super beneficial as it's the default shrinker for Android.

**Comment by akarnokd** [comment]
Does R8 even complain without those `-dontwarn` entries?

**Comment by vanniktech** [comment]
I haven't built a release version with the latest RxJava version. If I do, and I see those warnings, I'll come back to this issue.

**Pull request merged**
