### PR TITLE
Lock-Free-IndexRingBuffer

### PR DESCRIPTION
**Pull request by kbahr**
Distilled from the changes, removed need for "synchronized" keyword on several methods by changing the IndexSection to a rough version of a lock-free stack.  Before and after benchmarks on my system show an improvement on all tests, more so on the pure Add tests (not sure this is a likely real world test?).

### CODE REVIEW

**Comment by akarnokd** [comment]
Hello, 

I've looked at IndexedSection and it is basically an array based stack of indices. I've searched for such lock-free implementations and all I found was that it is not possible because the ABA problem and the fact that you can't do atomic CAS on both the counter and the array value. This is why all lock-free stacks are linked-node based. I found some highly [complicated approach](http://www.cs.tau.ac.il/~shanir/nir-pubs-web/Papers/Lock_Free.pdf) which has issues on its own.

**Comment by akarnokd** [comment]
I'm closing this as it doesn't work.

**Comment by kbahr** [comment]
Hi akarnokd,

Sorry I missed this until now - I was out of town and away from email when you left the first comment.  Do you have a test that shows it not working?  All of the tests in the package worked with the change on my system.

**Comment by akarnokd** [comment]
Yes. The following code hangs:
```java
package rxjava.issue;

import java.util.concurrent.atomic.AtomicInteger;

import rx.internal.util.IndexedRingBuffer.IndexSection;

public class PR1627 {
    public static void main(String[] args) throws InterruptedException {
        AtomicInteger p1 = new AtomicInteger();
        AtomicInteger p2 = new AtomicInteger();
        IndexSection irb = new IndexSection();
        Thread t1 = new Thread(() -> {
            for (; !Thread.currentThread().isInterrupted();) {
//                synchronized (irb) {
                    irb.pushIndex(0);
                    irb.popIndex();
//                }
                p1.incrementAndGet();
            }
        });
        Thread t2 = new Thread(() -> {
            for (; !Thread.currentThread().isInterrupted();) {
//                synchronized (irb) {
                    irb.pushIndex(1);
                    irb.popIndex();
//                }
                p2.incrementAndGet();
            }
        });

        t1.start();
        t2.start();

        for (int i = 0; i < 50; i++) {
            System.out.println("Progress: " + p1 + ", "  + p2);
            Thread.sleep(100);
        }
        
        t1.interrupt();
        t2.interrupt();
        
    }
}
```

If I run this program, the progress stalls after some time and the thread(s) hang in a loop. This demonstrates the ABA problem with array-based concurrent stacks. If I uncomment the synchronization block, the progress is apparent.

**Comment by kbahr** [comment]
Thanks for the simple test!  I'll try to rework the changes and keep your test in my back pocket to help verify further.  Thanks for the feedback!

**Comment by akarnokd** [comment]
No, you misunderstand me. What you try to accomplish is not possible. Just search for lock-free array based stack.

**Comment by kbahr** [comment]
I didn't misunderstand, I just didn't explain what I meant by rework.

The purpose of the stack is just to minimize growth of the buffer.  The buffer never compacts, it only grows so it uses some data structure (something stack-like currently) to hold "free" indeces.  My intention was to rework the way the buffer controls growth rather than fixate on maintaining a stack.

The goals/constraints of the class as I see them are to minimize object creation, minimize buffer growth, avoid expensive compaction, and achieve those in a lock-free manner.

**Comment by abersnaze** [comment]
I accept your challenge @akarnokd.  Here is my implementation of a lock free array based stack.  I took liberty with the term "array based" because it is actually a pre-allocated linked list.

```
package rx.internal.util;

import java.util.concurrent.atomic.AtomicIntegerFieldUpdater;

public class ArrayBasedLockFreeStack<T> {
    private final Object[] array;
    private final int[] next;
    @SuppressWarnings("unused")
    private volatile int head;
    @SuppressWarnings("unused")
    private volatile int free;

    @SuppressWarnings("rawtypes")
    public static AtomicIntegerFieldUpdater<ArrayBasedLockFreeStack> headUpdater = AtomicIntegerFieldUpdater.newUpdater(ArrayBasedLockFreeStack.class, "head");
    @SuppressWarnings("rawtypes")
    public static AtomicIntegerFieldUpdater<ArrayBasedLockFreeStack> freeUpdater = AtomicIntegerFieldUpdater.newUpdater(ArrayBasedLockFreeStack.class, "free");

    public ArrayBasedLockFreeStack(int size) {
        array = new Object[size];
        next = new int[size];
        for (int i = 1; i < size; i++) {
            next[i - 1] = i;
        }
        next[size - 1] = -1;
        head = -1;
        free = 0;
    }

    public boolean push(T t) {
        // capture a spot to put the value.
        int oldFree, newFree;
        do {
            oldFree = freeUpdater.get(this);

            // no room left
            if (oldFree == -1)
                return false;

            newFree = next[oldFree];
        } while (!freeUpdater.compareAndSet(this, oldFree, newFree));

        // put the value
        array[oldFree] = t;

        // update the head
        int oldHead, newHead;
        do {
            oldHead = headUpdater.get(this);
            next[oldFree] = oldHead;
            newHead = oldFree;
        } while (!headUpdater.compareAndSet(this, oldHead, newHead));

        // all done
        return true;
    }

    public T pop() {
        // capture a value from the head.
        int oldHead, newHead;
        do {
            oldHead = headUpdater.get(this);

            // no values left
            if (oldHead == -1)
                throw new IllegalStateException("stack is empty");

            newHead = next[oldHead];
        } while (!headUpdater.compareAndSet(this, oldHead, newHead));

        @SuppressWarnings("unchecked")
        T result = (T) array[oldHead];

        // add it to the free list
        int oldFree, newFree;
        do {
            oldFree = freeUpdater.get(this);
            next[oldHead] = oldFree;
            newFree = oldHead;
        } while (!freeUpdater.compareAndSet(this, oldFree, newFree));

        return result;
    }

    public boolean isEmpty() {
        return headUpdater.get(this) == -1;
    }
}
```

**Comment by akarnokd** [comment]
It seems to work, almost. If I run my program above, I get nulls popped pretty frequently. It works with concurrent linked deque. See the following program:
```java
import java.util.Deque;
import java.util.concurrent.ConcurrentLinkedDeque;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicIntegerFieldUpdater;

public class LockfreeStackTest {
    public static class ArrayBasedLockFreeStack<T> {
        private final Object[] array;
        private final int[] next;
        @SuppressWarnings("unused")
        private volatile int head;
        @SuppressWarnings("unused")
        private volatile int free;

        @SuppressWarnings("rawtypes")
        public static AtomicIntegerFieldUpdater<ArrayBasedLockFreeStack> headUpdater =
          AtomicIntegerFieldUpdater.newUpdater(ArrayBasedLockFreeStack.class, "head");
        @SuppressWarnings("rawtypes")
        public static AtomicIntegerFieldUpdater<ArrayBasedLockFreeStack> freeUpdater = 
          AtomicIntegerFieldUpdater.newUpdater(ArrayBasedLockFreeStack.class, "free");

        public ArrayBasedLockFreeStack(int size) {
            array = new Object[size];
            next = new int[size];
            for (int i = 1; i < size; i++) {
                next[i - 1] = i;
            }
            next[size - 1] = -1;
            head = -1;
            free = 0;
        }

        public boolean push(T t) {
            // capture a spot to put the value.
            int oldFree, newFree;
            do {
                oldFree = freeUpdater.get(this);

                // no room left
                if (oldFree == -1)
                    return false;

                newFree = next[oldFree];
            } while (!freeUpdater.compareAndSet(this, oldFree, newFree));

            // put the value
            array[oldFree] = t;

            // update the head
            int oldHead, newHead;
            do {
                oldHead = headUpdater.get(this);
                next[oldFree] = oldHead;
                newHead = oldFree;
            } while (!headUpdater.compareAndSet(this, oldHead, newHead));

            // all done
            return true;
        }

        public T pop() {
            // capture a value from the head.
            int oldHead, newHead;
            do {
                oldHead = headUpdater.get(this);

                // no values left
                if (oldHead == -1)
//                    throw new IllegalStateException("stack is empty");
                    return null;

                newHead = next[oldHead];
            } while (!headUpdater.compareAndSet(this, oldHead, newHead));

            @SuppressWarnings("unchecked")
            T result = (T) array[oldHead];
            array[oldHead] = null;

            // add it to the free list
            int oldFree, newFree;
            do {
                oldFree = freeUpdater.get(this);
                next[oldHead] = oldFree;
                newFree = oldHead;
            } while (!freeUpdater.compareAndSet(this, oldFree, newFree));

            return result;
        }

        public boolean isEmpty() {
            return headUpdater.get(this) == -1;
        }
    }

    public static void main(String[] args) throws InterruptedException {
        AtomicInteger p1 = new AtomicInteger();
        AtomicInteger p2 = new AtomicInteger();
//        ArrayBasedLockFreeStack<Integer> irb = new ArrayBasedLockFreeStack<>(8);
        Deque<Integer> irb = new ConcurrentLinkedDeque<>();
        
        Thread t1 = new Thread(() -> {
            for (; !Thread.currentThread().isInterrupted();) {
                irb.push(1);
                if (irb.pop() == null) {
                    p1.incrementAndGet();
                };
            }
        });
        Thread t2 = new Thread(() -> {
            for (; !Thread.currentThread().isInterrupted();) {
                irb.push(2);
                if (irb.pop() == null) {
                    p2.incrementAndGet();
                }
            }
        });

        t1.start();
        t2.start();

        for (int i = 0; i < 50; i++) {
            System.out.println("Progress: " + p1 + ", "  + p2);
            Thread.sleep(100);
        }

        t1.interrupt();
        t2.interrupt();

    }
}

**Comment by abersnaze** [comment]
the problem was trying to reuse the `next` array for both the head and free pointers.

```
package rx.internal.util;

import java.util.Deque;
import java.util.concurrent.ConcurrentLinkedDeque;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicIntegerFieldUpdater;

public class LockfreeStackTest {
    public static class ArrayBasedLockFreeStack<T> {
        private final Object[] array;
        private final int[] nextFree;
        private final int[] nextHead;
        @SuppressWarnings("unused")
        private volatile int head;
        @SuppressWarnings("unused")
        private volatile int free;

        @SuppressWarnings("rawtypes")
        public static AtomicIntegerFieldUpdater<ArrayBasedLockFreeStack> headUpdater = AtomicIntegerFieldUpdater.newUpdater(ArrayBasedLockFreeStack.class, "head");
        @SuppressWarnings("rawtypes")
        public static AtomicIntegerFieldUpdater<ArrayBasedLockFreeStack> freeUpdater = AtomicIntegerFieldUpdater.newUpdater(ArrayBasedLockFreeStack.class, "free");

        public ArrayBasedLockFreeStack(int size) {
            array = new Object[size];

            nextHead = new int[size];
            head = -1;

            nextFree = new int[size];
            for (int i = 1; i < size; i++) {
                nextFree[i - 1] = i;
            }
            nextFree[size - 1] = -1;
            free = 0;
        }

        public void push(T t) {
            // capture a spot to put the value.
            int oldFree, newFree;
            do {
                oldFree = freeUpdater.get(this);

                // no room left
                if (oldFree == -1)
                    throw new ArrayIndexOutOfBoundsException();

                newFree = nextFree[oldFree];
            } while (!freeUpdater.compareAndSet(this, oldFree, newFree));

            // put the value
            array[oldFree] = t;

            // update the head
            int oldHead, newHead;
            do {
                oldHead = headUpdater.get(this);
                nextHead[oldFree] = oldHead;
                newHead = oldFree;
            } while (!headUpdater.compareAndSet(this, oldHead, newHead));
        }

        public T pop() {
            // capture a value from the head.
            int oldHead, newHead;
            do {
                oldHead = headUpdater.get(this);

                // no values left
                if (oldHead == -1)
                    throw new IllegalStateException();
                if (oldHead == -2)
                    throw new ArrayIndexOutOfBoundsException();

                newHead = nextHead[oldHead];
            } while (!headUpdater.compareAndSet(this, oldHead, newHead));

            @SuppressWarnings("unchecked")
            T result = (T) array[oldHead];
            array[oldHead] = null;

            // add it to the free list
            int oldFree, newFree;
            do {
                oldFree = freeUpdater.get(this);
                nextFree[oldHead] = oldFree;
                newFree = oldHead;
            } while (!freeUpdater.compareAndSet(this, oldFree, newFree));

            return result;
        }

        public boolean isEmpty() {
            return headUpdater.get(this) == -2;
        }
    }

    public static void main(String[] args) throws InterruptedException {
        final AtomicInteger p1 = new AtomicInteger();
        final AtomicInteger p2 = new AtomicInteger();
        final ArrayBasedLockFreeStack<Integer> irb = new ArrayBasedLockFreeStack<Integer>(2);
        // final Deque<Integer> irb = new ConcurrentLinkedDeque<Integer>();

        Thread t1 = new Thread(new Runnable() {
            public void run() {
                for (; !Thread.currentThread().isInterrupted();) {
                    irb.push(1);
                    Integer x = irb.pop();
                    if (x == null) {
                        p1.incrementAndGet();
                    }
                }
            }
        });
        Thread t2 = new Thread(new Runnable() {
            public void run() {
                for (; !Thread.currentThread().isInterrupted();) {
                    irb.push(2);
                    Integer x = irb.pop();
                    if (x == null) {
                        p2.incrementAndGet();
                    }
                }
            }
        });

        t1.start();
        t2.start();

        for (int i = 0; i < 50; i++) {
            System.out.println("Progress: " + p1 + "\t" + p2);
            Thread.sleep(100);
        }

        t1.interrupt();
        t2.interrupt();

    }
}
```

**Comment by akarnokd** [comment]
That seems to work. I've run a [JMH benchmark](https://gist.github.com/akarnokd/6071deb98e92323f3672) and this is what I get:
```
Benchmark                            (loop)   Mode   Samples        Score  Score error    Units
r.i.LockfreeStackPerf.tpt            100000  thrpt         5       48,145        0,609    ops/s
r.i.LockfreeStackPerf.tpt:offer      100000  thrpt         5       23,948        0,549    ops/s
r.i.LockfreeStackPerf.tpt:poll       100000  thrpt         5       24,197        0,944    ops/s
r.i.LockfreeStackPerf.tpt           1000000  thrpt         5        4,837        0,064    ops/s
r.i.LockfreeStackPerf.tpt:offer     1000000  thrpt         5        2,423        0,052    ops/s
r.i.LockfreeStackPerf.tpt:poll      1000000  thrpt         5        2,414        0,020    ops/s
r.i.LockfreeStackPerf.tpt2           100000  thrpt         5       47,286        1,566    ops/s
r.i.LockfreeStackPerf.tpt2:offer2    100000  thrpt         5       23,612        0,973    ops/s
r.i.LockfreeStackPerf.tpt2:poll2     100000  thrpt         5       23,674        0,702    ops/s
r.i.LockfreeStackPerf.tpt2          1000000  thrpt         5        4,765        0,016    ops/s
r.i.LockfreeStackPerf.tpt2:offer2   1000000  thrpt         5        2,379        0,023    ops/s
r.i.LockfreeStackPerf.tpt2:poll2    1000000  thrpt         5        2,386        0,025    ops/s
```

It seems to be slightly faster within the error score.

**Pull request closed without merging**
