### PR TITLE
2.x: Add marbles for Single.concat operator

### PR DESCRIPTION
**Pull request by UMFsimke**
Here are marbles for `concat(Iterable)`, `concat(Publisher)`, `concat(Publisher, prefetch)`, `concat(Observable)`,  `concat(source1, source2)`, `concat(source1, source2, source3)`, `concat(source1, source2, source3, source4)` and `concatArray` operators that should close them at #5788 .

Marble for `concat(Iterable)`
concatIterable

Marble for `concat(Publisher)`
concatPublisher

Marble for `concat(Publisher, prefetch)`
concatPublisherN

Marble for `concat(Observable)`
concatObservable

Marble for `concat(source1, source2)`
concat2

Marble for `concat(source1, source2, source3)`
concat3

Marble for `concat(source1, source2, source3, source4)`
concat4

Marble for `concatArray`
concatArray

Please pay attention to file names in javadoc as I was not sure how to name `concat(Iterable)` so I've added at the end `i`, for `concat(Observable)` I've added `o`. For `concat(source1, source2, source3)` and `concat(source1, source2, source3, source4)` I've used `n` and `m` as they are numerical values.

Also, is there an error in `concat(Publisher)` and `concat(Publisher, prefetch)` with `request()` commands? I did used as a reference `Completable.concat(Publisher)` marble but I do not understand why do we have `request(1)` after first event as we already requested prefetching of multiple ones. Is it because others are still not produced?

Thanks

### CODE REVIEW

**Comment by akarnokd** [comment]
- Please color the marbles in the sequences differently to each other.
- Since some inputs and outputs are `Observable`s and `Flowable`s, their terminal event idicator is a pass-throug arrow: `----|----->` and `----X----->`. Please update these diagrams accordingly.
- Use `Single.concat.o3.png` and `Single.concat.o4.png`.
 - The `X` in the middle of the left side of `concat(Publisher, prefetch)` is misaligned.
- Multiple requests are there to reinforce those are `Flowable`s and thus more requests may come even if there was some initial request before. Keep them in the diagram.

**Comment by UMFsimke** [comment]
Thanks for explanation!

Marbles are now updated per comments

**Comment by akarnokd** [comment]
The `concat(Publisher)` and `concat(Publisher, int)` diagram's input side and inside the box are still `---->|`

**Comment by UMFsimke** [comment]
Based on a comment I thought that only `Observable`s and `Flowable`s should be updated. Those images are now updated with `----|---->`

**Review by akarnokd — APPROVED** [review]

**Pull request merged**
