### PR TITLE
Observable.java - remove unnecessary SuppressWarnings annotations

### PR DESCRIPTION
**Pull request by davidmoten**
a little bit of cleanup. I think these have been hanging around since we were using varargs parameters.

### CODE REVIEW

**Comment by akarnokd** [comment]
I think the ```@SuppressWarning``` is necessary because without them, the ```Array.asList``` calls give warnings about generic array creation (in Eclipse at least).

**Comment by davidmoten** [comment]
yep you are right. I used Eclipse with JDK 7 and gave warnings when annotations present. Now am looking at same with Eclipse + JDK 8 and no warnings. I'll close.

**Comment by iNoles** [comment]
Java 7 has another annotation to fix that warning. http://blog.jetbrains.com/idea/2011/04/java-7-safevarargs/

**Comment by akarnokd** [comment]
@iNoles RxJava has to remain compatible with Java 6.

**Pull request closed without merging**
