### PR TITLE
Create a base test class and have all unit tests extend it

### PR DESCRIPTION
**Pull request by RomanWuattier**
This commit creates the `RxJavaTest` class defining a default
timeout to 5 minutes. An ignored test announce itself for each
running class extending it preventing Travis CI from killing the
build.

Have `Completable` tests extend from `RxJavaTest`.
Have `Disposable` tests extend from `RxJavaTest`.
Have `Exception` tests extend from `RxJavaTest`

Related: #6583

### CODE REVIEW

**Review by akarnokd — APPROVED** [review]

**Comment by RomanWuattier** [comment]
Thanks for updating the description and the review. I amended the commit to meet the new PR description.
I will cut the issue into a few more pull requests for simple readability reasons.

**Review by vanniktech — APPROVED** [review]

**Comment by akarnokd** [comment]
@RomanWuattier do you want to do the rest of the test classes in a separate PR?

**Comment by RomanWuattier** [comment]
@akarnokd yes, you can merge this one when you want to.

**Review by akarnokd — APPROVED** [review]

**Comment by RomanWuattier** [comment]
Thanks!

**Pull request merged**
