### PR TITLE
2.x: upgrade to Gradle 2.14

### PR DESCRIPTION
**Pull request by akarnokd**
Upgrade to 2.14.

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Wait!

**Comment by artem-zinnatullin** [comment]
You just updated link to gradle wrapper, but you haven't run any gradle task and it didn't download new `gradlew` shell flies and new `gradle-wrapper.jar`

Just run gradle, ie: `./gradlew --version`, it should update wrapper files and then you need to add them to PR.

**Comment by akarnokd** [comment]
https://travis-ci.org/ReactiveX/RxJava/builds/140744064#L274

**Comment by akarnokd** [comment]
```
C:\Users\akarnokd\git\RxJava>gradlew --version

------------------------------------------------------------
Gradle 2.14
------------------------------------------------------------

Build time:   2016-06-14 07:16:37 UTC
Revision:     cba5fea19f1e0c6a00cc904828a6ec4e11739abc

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Windows 7 6.1 amd64

C:\Users\akarnokd\git\RxJava>
```

**Comment by artem-zinnatullin** [comment]
Right, but for next PR gradle wrapper files will be marked as changed and will have to be commited.

Can you check what `git status` shows for you now? `gradle/wrapper/gradle-wrapper.jar` should be marked as changed, `./gradlew` and `./gradlew.bat` can be changed too.

**Comment by gabrielittner** [comment]
You have to run `./gradlew wrapper` to update the wrapper files.

**Comment by akarnokd** [comment]
Okay.

**Comment by artem-zinnatullin** [comment]
That's better, 👍

**Pull request merged**
