### PR TITLE
Add maxConcurrent parameter to flatMapIterable

### PR DESCRIPTION
**Pull request by lukaciko**
Refs #3711. Should these new overloaded functions be annotated with `@Beta`?

### CODE REVIEW

**Comment by lukaciko** [comment]
The failing test (`testNoMoreRequestsAfterUnsubscribe`) seems unrelated. All tests pass locally.

**Comment by akarnokd** [comment]
If you could add one unit test for each method that verifies maxConcurrent is honored, that would be great.

**Comment by lukaciko** [comment]
While writing the test I figured you might have been right when commenting on issue #2627. If I am not mistaken all the observables created with `OperatorMapPair.convertSelector` use the same scheduler (there is no way to subscribe them to different schedulers) and thus are run sequentially and until completion. Would adding a Scheduler parameter make sense?

**Comment by akarnokd** [comment]
There is no scheduler involved here so no.

**Comment by akarnokd** [comment]
:+1: as it is now

**Comment by stevegury** [comment]
:+1:

**Pull request merged**
