### PR TITLE
2.x: sys-property to disable calling uncaught exception handler

### PR DESCRIPTION
**Pull request by akarnokd**
This PR adds a new system property `rx2.onerror-nouncaught` to suppress calling the current thread's uncaught exception handler with the default `RxJavaPlugins.onError` as it crashes Android apps (on desktop, it either does nothing or prints the stacktrace).

Related: #4894, #4871, #4863, #4807

### CODE REVIEW

**Comment by JakeWharton** [comment]
Not sure how comfortable I am with the behavior of this, or the library in general, around the distinction between undeliverable errors due to violating the observable contract and undeliverable errors due to disposal. In the latter case, I feel like sending these to the plugins isn't the behavior I would expect. I rely on my app to crash when a notification to onError throws. How are users supposed to distinguish between errors that simply couldn't be delivered because the observer left or serious problems in error handling code?

**Comment by artem-zinnatullin** [comment]
Agreed.

> I feel like sending these to the plugins isn't the behavior I would expect.

+1, I don't see much difference between errors and values being sent to /dev/null in case when observer stopped listening for the stream.

What about reporting error that have no observers to the Plugin only if it's `java.lang.Error`, such as `OutOfMemory` or `VirtualMachineError`?

**Comment by akarnokd** [comment]
> errors due to disposal. In the latter case, I feel like sending these to the plugins isn't the behavior I would expect.

It is up to the source to decide if the error it is about to send should be considered significant or not. For example, `InterruptedIOException` that is thrown by the Retrofit adapter may check for `isDisposed` and not emit the error.

Generally, the end application developer should set up a handler via `RxJavaPlugins.setErrorHandler` and not let the error reach the current thread's uncaught error handler.

**Comment by JakeWharton** [comment]
> What about reporting error that have no observers to the Plugin only if it's java.lang.Error, such as OutOfMemory or VirtualMachineError?

These should always automatically be going to the thread's uncaught handler due to the `throwIfFatal` checks.

> Generally, the end application developer should set up a handler via RxJavaPlugins.setErrorHandler and not let the error reach the current thread's uncaught error handler.

What are we supposed to do with these errors? If we can't differentiate between failures during onError and normal onErrors undeliverable due to dispose then how do we know what's crash worth vs. not? The former should absolutely crash the VM but I don't care about the latter at all.

**Comment by akarnokd** [comment]
RxJava can't decide for the user or for libraries building upon it. All it can do is to either provide a channel for undeliverable exceptions or suppress all of them but if RxJava by default suppressed such errors, there is no "unsuppress" them later.

For the Retrofit case, I think the catch handler that receives the `InterruptedIOException` should check for `isDisposed`/`isCancelled` to detect that the exception is due to cancellation and not some other reason.

Otherwise, I'm not too keen on this PR and one can just simply call `RxJavaPlugins.setErrorHandler(Throwable::printStackTrace)` to bypass the current thread handler.

**Pull request closed without merging**
