### PR TITLE
2.x: Remove defunct 'Nbp' prefix from Observable interfaces.

### PR DESCRIPTION
**Pull request by JakeWharton**

### CODE REVIEW

**Comment by JakeWharton** [comment]
All other 'Nbp' references are in tests which I'll clean up next.

**Comment by JakeWharton** [comment]
Also worth noting that these names are the same now as those in `Flowable`, but you're not only unlikely to use both in the same file, the disambiguation of the two is trivial with an `Observable.` or `Flowable.` qualifier.

**Comment by akarnokd** [comment]
:+1:

**Comment by vanniktech** [comment]
What about `NbpFullArbiter` & `NbpQueueDrain`? They are not in the test scope.

**Comment by JakeWharton** [comment]
Yeah I saw those after commenting.

**Pull request merged**
