### PR TITLE
1.x: enhance generics doOnError doOnRequest

### PR DESCRIPTION
**Pull request by davidmoten**
want to able to call `doOnError(Action1<Object>)` and similarly enhanced `doOnRequest` while I was about it.

### CODE REVIEW

**Review by JakeWharton — APPROVED** [review]
Test to ensure bounds are maintained?

**Comment by davidmoten** [comment]
> Test to ensure bounds are maintained?

I've added a couple of tests to get coverage of new lower bounds.

**Comment by akarnokd** [comment]
Is it okay if this goes into 1.2 only ? Technically this isn't a behavior change but an API change, and besides o f `doOnRequested` upgrading to standard, `doOnError` was established earlier.

**Comment by davidmoten** [comment]
OK with me to go in 1.2.

**Comment by akarnokd** [comment]
Oh, something conflicted. Could you rebase?

**Comment by davidmoten** [comment]
rebased.

**Comment by akarnokd** [comment]
Thanks :+1:

**Pull request merged**
