### PR TITLE
[3.x] Remove deprecated method from 2.x

### PR DESCRIPTION
**Pull request by JakeWharton**

### CODE REVIEW

**Comment by akarnokd** [comment]
I kept this so that when writing a standard method, one doesn't accidentally null-check an auto-boxed primitive.

**Comment by JakeWharton** [comment]
I see. I was about to remove `ObjectsHelper.requireNonNull` in favor of `Objects.requireNonNull`.

**Comment by akarnokd** [comment]
Well, if all uses get replaced with `Objects.requireNonNull`, this overload wouldn't come into play. I suppose `Objects.requireNonNull` is desugared and inlined across all API levels already, right?

**Comment by JakeWharton** [comment]
Yep! It's actually the first API that was desugared and has been supported since AGP 3.2.

**Comment by akarnokd** [comment]
Okay then.

**Pull request merged**
