### PR TITLE
Standardize java source headers

### LINKED ISSUE #7204: 3.x: Convert License from dangling Javadoc to block comment
The License block at the beginning of all java files is a dangling Javadoc which results in a minorly annoying warning in Intellij. Convert all headers to regular Java block comment. Licenses are not all standardized across files. Use most common License as standard.

Update Checkstyle to validate all Java files have License header. Remove custom unit test FixLicenseHeaders currently used to validate License.

### PR DESCRIPTION
**Pull request by benjamintboyle**
Convert License headers to block comments instead of dangling Javadoc comments. Use Checkstyle to validate Java source files have Licenses attached. Updated Checkstyle to most recent version. Updated Checkstyle configuration to remove mostly commented out code and update to correct DTD.

Removed unit test FixLicenseHeaders as the functionality is handled by the Checkstyle header validation.

One commit is Checkstyle and Gradle updates. Second commit is for all the Java source License updates.

Fixes #7204

### CODE REVIEW

**Comment by akarnokd** [comment]
Please don't remove the FixLicenseHeaders.

**Comment by akarnokd** [comment]
Also please do not change the license start date, it should be 2016.

**Comment by benjamintboyle** [comment]
Will fix. Do you have an issue with the header validation in Checkstyle being an error as I have it, or should I change it to a warning? I saw in comments on other commits that errors might not be welcome from Checkstyle.

**Comment by benjamintboyle** [comment]
Also should all the Licenses have a 2016 date? I saw a handful of them that had different dates (i.e. 2017).

**Review by akarnokd — APPROVED** [review]

**Pull request merged**
