### PR TITLE
Enable maven central sync via bintray

### PR DESCRIPTION
**Pull request by rspieldenner**

### CODE REVIEW

**Comment by benjchristensen** [comment]
Thank you!

**Comment by benjchristensen** [comment]
@rspieldenner I got this error, is it an issue with config or just a transient issue?

https://travis-ci.org/ReactiveX/RxJava/builds/57801257#L3427


Last Sync Errors: Could not sync artifact rxjava-1.0.9-benchmarks.jar. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html> Could not sync artifact rxjava-1.0.9-benchmarks.jar.sha1. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html> Could not sync artifact rxjava-1.0.9-sources.jar. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html> Could not sync artifact rxjava-1.0.9-sources.jar.sha1. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html> Could not sync artifact rxjava-1.0.9.pom.asc. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html> Could not sync artifact rxjava-1.0.9-javadoc.jar. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html> Could not sync artifact rxjava-1.0.9-javadoc.jar.sha1. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html> Could not sync artifact rxjava-1.0.9.jar.asc. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html> Could not sync artifact rxjava-1.0.9-javadoc.jar.asc. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html> Could not sync artifact rxjava-1.0.9.jar. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html> Could not sync artifact rxjava-1.0.9.jar.sha1. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html> Could not sync artifact rxjava-1.0.9-sources.jar.asc. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html> Could not sync artifact rxjava-1.0.9.pom. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html> Could not sync artifact rxjava-1.0.9.pom.sha1. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html> Could not sync artifact rxjava-1.0.9-benchmarks.jar.asc. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html> Could not sync artifact rxjava-1.0.9-benchmarks.jar.md5. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html> Could not sync artifact rxjava-1.0.9-sources.jar.md5. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html> Could not sync artifact rxjava-1.0.9-javadoc.jar.md5. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html> Could not sync artifact rxjava-1.0.9.jar.md5. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html> Could not sync artifact rxjava-1.0.9.pom.md5. Server response: <html> <head> <title>403 - Forbidden</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">  <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.11.2-06" type="text/css" media="screen" title="no title" charset="utf-8"> </head> <body> <h1>403 - Forbidden</h1> <p>User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173</p> </body> </html>

**Comment by benjchristensen** [comment]
I was able to manually sync from Bintray, but I want to know if it is something about the Gradle sync that we don't have configured right.

**Comment by rspieldenner** [comment]
Not sure. We had one of the nebula plugins have similar problems. I will
take a look and see if it is something we're doing or if it was a blip on
bintray.

About at what time did this happen?

**Comment by rspieldenner** [comment]
Is this the first release since I added the sonatypeUsername?

**Comment by rspieldenner** [comment]
And I have a theory, I probably used another set of sonatype Credentials that don't have permission to push to io.reactivex. Do you know if RxGroovy or RxScala have been able to publish with what I setup?

**Pull request merged**
