### PR TITLE
new method concatMapIterable #3713

### PR DESCRIPTION
**Pull request by ginbalin**
new method concatMapIterable #3713

### CODE REVIEW

**Comment by stevegury** [comment]
Thanks @ginbalin for the addition, could you also add a test please?

**Comment by ginbalin** [comment]
Added a simple test. Is this enough?

**Comment by stevegury** [comment]
:+1:

**Comment by akarnokd** [comment]
Please squash your commits.

**Comment by ginbalin** [comment]
Done

**Comment by akarnokd** [comment]
:+1:

**Pull request merged**
