### PR TITLE
Remove redundant variables

### PR DESCRIPTION
**Pull request by vbauer**
Remove redundant variables from the following classes:

* OperatorTimeoutBase
* EventLoopsScheduler

### CODE REVIEW

**Comment by benjchristensen** [comment]
Often times developers use redundant variables for clarity.

**Comment by vbauer** [comment]
I know that it is common practice for some developers, but I'm not sure that clarification via completely unnecessary variables is a good way / code design. All static analysis tools (like PMD, Findbugs, Checkstyle, Inspections from IDEA) agree with this. I think it will be better to have self-documented code which is well-formed for reading and debugging without this variables.

**Comment by benjchristensen** [comment]
This is why we don't use PMD, Checkstyle, etc on this project, because every developer has a different subjective opinion.

**Comment by vbauer** [comment]
Actually, this tools should prevent argues and stop subjective-thinking (to minimize human-related errors, to make a common code style, etc.), but I understand your opinion and you can reject this PR.

**Comment by akarnokd** [comment]
Cosmetic change in internal classes, I don't think it's worth it.

**Comment by stealthcode** [comment]
RxJava project does not have a style guide line for contributions. My initial thoughts are that the original committer of this particular code thought it was important to have a named value (potentially for ease of debugging or renaming in context) so it would be best to leave it as is. That said, if there were changes that you were making to the functionality then you might find it necessary or beneficial to collapse them (i.e. condense the code for readability) and so long as it wasn't too far off from the general style of the surrounding code then it would be just fine. Closing.

**Pull request closed without merging**
