### PR TITLE
Remove redundant final modifier from static method in Actions

### PR DESCRIPTION
**Pull request by artem-zinnatullin**

### CODE REVIEW

**Comment by akarnokd** [comment]
This will conflict with #3123.

**Comment by artem-zinnatullin** [comment]
Yep, I saw #3123, that's why I didn't remove `T9`.

If you'll merge #3123 I'll just update this PR.

**Comment by akarnokd** [comment]
I've merged #3123, could you update this PR?

**Comment by artem-zinnatullin** [comment]
Updated!

**Comment by akarnokd** [comment]
Great!

**Pull request merged**
