### PR TITLE
Adding support for Intellij IDEA project generation

### PR DESCRIPTION
**Pull request by Valloric**
(All in title.)

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
It works just fine as is tho

**Comment by akarnokd** [comment]
I've been working with the code base in both Eclipse and IntelliJ without import problems. I believe the `eclipse` and `idea` plugins are there to generate some project structure outside the IDEs, but I find it much more easy to let the respective IDE's simply import RxJava as Gradle project.

**Comment by vanniktech** [comment]
Same here.

**Comment by Valloric** [comment]
I'll take your word then; I'm used to doing `gradle idea` to generate the project files.

**Pull request closed without merging**
