### PR TITLE
Adding NonNull annotations to Observable & Single

### PR DESCRIPTION
**Pull request by freakomonk**
Adding NonNull annotations in factory methods for improved code compilation

Resolves: #6309

### CODE REVIEW

**Comment by freakomonk** [comment]
#6309 @akarnokd Can you pls take a look at this and review ?

**Comment by akarnokd** [comment]
Thanks for Contributing. A few points:
- You don't have to keep the welcome text of the PR, that's for telling contributors what to do. See the updated text for future reference.
- Didn't you mean to add `@NonNull` to the arguments rather than to the return value?

**Review by vanniktech — COMMENTED** [review]
I like it. Kotlin currently warns about those since it's not capable of inferring whether they can be null or not. 

Annotation order should be the same for all usages. This will mix this up.

Can't we use a nonnull by default kind of annotation since 99 percent of the API only uses non null?

**Comment by akarnokd** [comment]
Non-null by default came up in #5341 but not sure what happened. I'd think it was a JSR 305 annotation instead of just a convention thus the IDEs simply wouldn't have supported them.

@freakomonk Did you also want to add these to `Maybe`, `Flowable` and `Completable` static methods?

**Comment by freakomonk** [comment]
@vanniktech Can you elaborate `nonNull by default` ?

**Comment by freakomonk** [comment]
@akarnokd Thanks for the suggestions. Will keep in mind henceforth. 

I added the `@NonNull` annotation to methods with ` ObjectHelper.requireNonNull` check in them. As the input params are being checked for `null`, I am checking for the return value.

I have updated the `Flowable` static methods but do not see any `Maybe`, `Completable` that do not have already have this annotation.

**Comment by vanniktech** [comment]
> Non-null by default came up in #5341 but not sure what happened. I'd think it was a JSR 305 annotation instead of just a convention thus the IDEs simply wouldn't have supported them.

This @freakomonk. I'm not sure though which annotations works where and what needs to be enabled/disabled or not. Either we look into this or we just use RxJava's NonNull annotation which does the job.

**Comment by freakomonk** [comment]
@akarnokd  Hi David. Is there something else to do to get this PR merged ?

**Comment by akarnokd** [comment]
@freakomonk I was waiting for you to add them to the other reactive base classes.

**Comment by freakomonk** [comment]
@akarnokd Added annotation to further methods now. Can you pls check ?

**Comment by freakomonk** [comment]
@akarnokd Is this now okay to be merged ? Your review pls

**Review by akarnokd — APPROVED** [review]

**Pull request merged**
