### PR TITLE
2.x: Document and test amb subscription ordering.

### PR DESCRIPTION
**Pull request by JakeWharton**
Refs #5044.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Once wording and tests are approved I'll port to 1.x as well.

**Review by akarnokd — APPROVED** [review]
Nice!

(Forgot about testing all signal types as well, so 5 x 3 x 3, but I don't require it.)

**Comment by JakeWharton** [comment]
Hmm I seem to be fighting the cool documentation checker which is being a bit too clever in this instance. I'm using the word "Subscription" at the beginning of a sentence which it thinks means `Subscription` the type. I'll figure out a wording tweak to make it end up as a lowercase "subscription".

**Comment by JakeWharton** [comment]
Also with regard to signal types, I figure the other tests cover those already so in these cases we're just guarding against ordering changes.

**Comment by akarnokd** [comment]
Yes, lowercase it as `Subscription` is interpreted as the reference to the type.

**Pull request merged**
