### PR TITLE
Remove @NonNull annotation in Consumer method parameter

### LINKED ISSUE #5442: 2.x: Consumer contract is violated when using doOnEvent
The following code showcases the problem:
```java
Completable.complete()
  .doOnEvent(t -> {})
```
`t` in this case is annotated with `@NonNull` but it will be `null` since the completable completes.

This is a real pain in Kotlin since the following code crashes in runtime:
```kotlin
Completable.complete()
  .doOnEvent {}
```

### PR DESCRIPTION
**Pull request by ansman**
This fixes #5442

### CODE REVIEW

**Comment by ansman** [comment]
This should be safe to merge, see the discussion in #5216

**Comment by ansman** [comment]
I'm curious, why did the code coverage decrease because of this?

**Comment by akarnokd** [comment]
There are unit tests that race for a certain code path inside the operators. Travis-CI lately has become 2-3x slower and often these code paths are no longer exercised. It is sometimes +/- 0.2%. If there is a generic drop unrelated to your changes, there is nothing to worry about.

**Review by artem-zinnatullin — APPROVED** [review]

**Comment by akarnokd** [comment]
Looks like this nullability thing is hitting many Kotlin users now (see #5448). What do you think about removing all nullability annotations from the functional types in an additional PR?

**Comment by svenjacobs** [comment]
> What do you think about removing all nullability annotations from the functional types

@akarnokd To add my two cents ;) I think this is a good idea. There is nothing wrong with nullability annotations as long as the code adheres to this contract - meaning `null` should never be passed where `@NonNull` is declared.

**Comment by akarnokd** [comment]
Java 6 doesn't enforce this and only Java 8+ allows annotating the type arguments themselves:

```java
public Observable<T> doOnNext(Consumer<@NonNull T> onNext);

public Completable doOnEvent(Consumer<@Nullable Throwable> onEvent);
```

**Comment by ansman** [comment]
@akarnokd I'd be happy to add a PR for removing them if you wish.
Should all annotations in the `io.reactivex.functions` package be removed then?

**Comment by akarnokd** [comment]
Looks like `Function` is the next to be adjusted: #5448 indicates it's return type may be null with `groupBy`. I'd delay removing all annotations in case Kotlin comes to senses because I doubt RxJava is the only library that has inconsistent nullability annotation usage.

**Comment by svenjacobs** [comment]
> Looks like Function is the next to be adjusted: #5448 indicates it's return type may be null with groupBy. I'd delay removing all annotations in case Kotlin comes to senses because I doubt RxJava is the only library that has inconsistent nullability annotation usage.

@akarnokd What do you mean by "Kotlin comes to senses"? This is by language design and I doubt it will change. I don't understand why we have to discuss this and why it's not clear that as a library developer you should not put `null` into an argument that is annotated by `@NonNull`. As I said before this is not a Kotlin-only problem and certainly will affect Java developers too as here clearly the contract is broken.

**Comment by akarnokd** [comment]
RxJava is a Java 6 library and thus we are bound by the capabilities of Java language level 6. We are also trying to be nice with other languages but that has limits. The best we can do is to remove nullability annotations from controversial functional types that come up.

What I mean by "senses" is it would be Kotlin's responsibility to work with native Java libraries and provide workaround since Java's type system doesn't have a primary notion of nullability; I just leave off/replace the annotations to satisfy some static analysis tools if necessary. The fact that just by upgrading to 1.1.3 compatiblity broke indicates there has to be work done on Kotlin's part.

**Comment by svenjacobs** [comment]
I'm aware that Java 6 cannot check nullability constraints during compile time. However this is not a language issue. IDEs like Intellij IDEA will analyze these annotations and give hints. So as a developer you might think that the argument can never be `null` but in fact it can. So what is the point of this annotation then?

**Comment by akarnokd** [comment]
See #5151. If we could support callsite nullability, we'd do it but we can't. So either annotate for the majority uses or not annotate at all through the common functional interfaces. Adding/removing annotations is considered binary compatible thus any other means, such as alternate interfaces has to be added and accompanied by new methods which also need to be named differently to avoid lambda ambiguity.

> IDEs like Intellij IDEA will analyze these annotations and give hints

The keyword is "hints", the annotations were mostly working for Java/Android but Kotlin no longer considers them as hints. If there was a "I take my chances" type/hint or you could disable the RxJava annotations being considered, that would make things simpler.

**Comment by JakeWharton** [comment]
If they're just hints I'd prefer them entirely removed. They should either
be 100% accurate or entirely absent. We have Java tools which take these
annotations as being 100% accurate and having anything less than that in
actuality will cause bugs.

**Comment by akarnokd** [comment]
AFAIK, the problem with the non-annotated interfaces was that IntelliJ/Kotlin inferred all of them as nullable T and caused inconveniences.

**Comment by JakeWharton** [comment]
Non-annotated types will be inferred as a "platform type" which has
ambiguous nullability. This allows the user to specify it as nullable or
non-nullable (with a runtime check in the latter case) based on what they
know of the data and operator.

**Comment by akarnokd** [comment]
So far, these were the cases that require the removal of annotations:

1) `Consumer` may be called with null (i.e.,`doOnEvent`)
2) `BiConsumer` may be called with null (i.e., `subscribe`)
3) `Function` may return null in `groupBy`'s key selector

The other functional types are never called with null and are not allowed to return null. Option 3 has no PR yet.

**Comment by ansman** [comment]
@akarnokd I added a PR for 3 in #5449

**Comment by akarnokd** [comment]
Thanks @ansman !

**Comment by svenjacobs** [comment]
> The fact that just by upgrading to 1.1.3 compatiblity broke indicates there has to be work done on Kotlin's part.

It just indicates that there were "holes" in the type system which have been fixed ;) Anyway thanks to everybody that this issue has been resolved!

**Pull request merged**
