### PR TITLE
2.x: Publish code coverage results to codecov.io

### PR DESCRIPTION
**Pull request by zsxwing**
Same as #4046 except the badge link.

### CODE REVIEW

**Comment by akarnokd** [comment]
:+1:

**Comment by artem-zinnatullin** [comment]
👍 @zsxwing can you also enable commits status check in codecov settings?

**Comment by zsxwing** [comment]
@artem-zinnatullin which button is for commits status check?

**Comment by artem-zinnatullin** [comment]
@zsxwing they've recently made major update and moved most of the settings to `codecov.yml`, looks like commit status check is now also lives there: https://codecov.io/docs#yaml_default_commit_status

**Comment by zsxwing** [comment]
> Codecov will enable three unique commit statuses by default

@artem-zinnatullin I think it's enabled already.

**Comment by artem-zinnatullin** [comment]
@zsxwing hm, but I don't see status checks from Codecov on GitHub, only report from Travis. Did you give required permissions to Codecov on GitHub? Probably configuration of ReactiveX organization does not allow transparent access to repos for apps authorized by its members.

**Comment by zsxwing** [comment]
@artem-zinnatullin Figured it out. Need some admin to click the `Create New Webhook` button in this page: https://codecov.io/gh/ReactiveX/RxJava/settings. @benjchristensen or @abersnaze can do it.

**Comment by artem-zinnatullin** [comment]
Yeah, thanks @zsxwing.

@abersnaze can you please allow Codecov to post commit statuses to the project like Travis is doing now? https://codecov.io/gh/ReactiveX/RxJava/settings

This will ensure that coverage fail (significant decrease/etc) is visible on the [Pull Requests list page](https://github.com/ReactiveX/RxJava/pulls) and will block/mark_as_yellow the merge button.

**Pull request merged**
