### PR TITLE
2.x: fix images of firstElement, flattenAsX, flatMapIterable

### PR DESCRIPTION
**Pull request by akarnokd**
This PR links in the new images from #5130 for previously misleading marble diagrams of the operators.

### CODE REVIEW

**Comment by akarnokd** [comment]
### Plus UnicastX:

Image
Image

**Review by vanniktech — APPROVED** [review]
Those height & width resizes are due to the new images, right?

**Comment by akarnokd** [comment]
Yes, the default with is set to 640 and these new images are slightly bigger in their native form.

**Review by JakeWharton — COMMENTED** [review]
:+1:

**Comment by akarnokd** [comment]
Thanks for the reviews guys!

**Pull request merged**
