### PR TITLE
add Dump debug method

### PR DESCRIPTION
**Pull request by isaiah**
Add a shortcut to dump the sequence and display message for complete and error event. Its usage is demonstrated in [Introduction to Rx](http://www.introtorx.com/Content/v1.0.10621.0/07_Aggregation.html). I think it's very convenient for newbies to play with different type of Observables.

### CODE REVIEW

**Comment by akarnokd** [comment]
I've resisted the urge to add such method to the observable because the dump style changes from place to place.

**Comment by JakeWharton** [comment]
Yeah, agreed. Also on Android we'd want it sending to `android.util.Log` with the string being used as the tag, not in the message.

I think this is one of those things that's so simple that it will be impossible to include because there's so many different things people will want from it.

**Comment by benjchristensen** [comment]
Generally the approach to debugging is left to methods such as `doOnNext`, `donNextComplete`, `doOnError`, `doOnEach`, `doOnSubscribe`, `doOnUnsubscribe`.

We have avoided logging in RxJava for the reasons @akarnokd and @JakeWharton gave. Thank you for providing this but I'm going to close this out and not add it.

**Comment by isaiah** [comment]
Sorry for the spam, I mistook it as part of the C# implementation.

**Pull request closed without merging**
