### PR TITLE
(refactor) some opportunities to use lambda functions

### PR DESCRIPTION
**Pull request by desmorto**
Thank you for contributing to RxJava. Before pressing the "Create Pull Request" button, please consider the following points:

  - [ ] Please give a description about what and why you are contributing, even if it's trivial.

  - [ ] Please include the issue list number(s) or other PR numbers in the description if you are contributing in response to those.

  - [ ] Please include a reasonable set of unit tests if you contribute new code or change an existing one. If you contribute an operator, (if applicable) please make sure you have tests for working with an `empty`, `just`, `range` of values as well as an `error` source, with and/or without backpressure and see if unsubscription/cancellation propagates correctly.

### CODE REVIEW

**Comment by JakeWharton** [comment]
This library targets Java 6 so this isn't feasible

**Review by ghost — COMMENTED** [review]
Nice, but as long as `RxJava` would target Java 6 (this primarily concerns the Android devices with system older than 4.2) this PR wouldn't be usable.

**Comment by akarnokd** [comment]
RxJava 2 has to stay Java 6 compatible.

**Comment by desmorto** [comment]
ok, thx for the feedback :+1:

**Pull request closed without merging**
