### PR TITLE
Add Single.finallyDo()

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
@akarnokd I've found a problem with `null` action, I'll create separate issue about this soon.

### CODE REVIEW

**Comment by akarnokd** [comment]
Could you verify what happens ig the callback throws?

One should check null in assembly time (i.e. when calling Single.finallyDo.

**Comment by artem-zinnatullin** [comment]
@akarnokd unfortunatelly very bad thing happens — not only this exception will be swallowed, but also `finallyAction` executed twice… I'm investigating this and will create issue soon.

**Comment by akarnokd** [comment]
:+1:

**Comment by abersnaze** [comment]
um... I just noticed that we `doOnTerminate` and `finallyDo` on `Observable`.

the number of methods is too damn high

Could we make this look like `doOn*()`?

**Comment by JakeWharton** [comment]
`doOnTerminate` happens before subscriber notification. `finallyDo` happens after.

**Comment by artem-zinnatullin** [comment]
Rebased

**Comment by akarnokd** [comment]
It can be called `doOnAfterComplete()` but since `finallyDo` is established, I'm not sure this rename can happen for 1.0.x.

**Comment by stealthcode** [comment]
I'd rather it were called doAfterComplete. finallyDo only exists for the Observable and it doesnt follow the do* convention. We could choose to have 2 conventions (naming Single's variant similarly) or deprecate Observable#finallyDo and create Observable#doAfterComplete. I vote for the latter naming them both doAfterComplete.

**Comment by JakeWharton** [comment]
I think it would have to be doAfterTermination since it runs on both
complete and error.

**Comment by stealthcode** [comment]
Does anyone have any objection to creating `Observable.doAfterTermination` as an alias for `finallyDo` and deprecating the original `finallyDo`? If that's acceptable then this PR should name it `Single.doAfterTermination`.

**Comment by akarnokd** [comment]
:+1: `doAfterTermination`

**Comment by davidmoten** [comment]
A bit of consistency in tenses would be nice though.

We have 
```
doOnCompleted
doOnTerminate
doOnSubscribe
doOnRequest
...
```
`doOnCompleted ` is the odd one out but may as well live with that. To be consistent call the method in question `doAfterTerminate` or `doAfterTerminated`?

**Comment by stealthcode** [comment]
I think `doAfterTerminate` sounds best to me. It's consistent with the
onComplete of 2.x

**Comment by artem-zinnatullin** [comment]
Renamed to `doAfterTerminate` & rebased, PTAL.

**Comment by stealthcode** [comment]
> Does anyone have any objection to creating Observable.doAfterTermination as an alias for finallyDo and deprecating the original finallyDo? 

@artem-zinnatullin would you like to deprecate `finallyDo` -> `doAfterTerminate` in this PR?

**Comment by artem-zinnatullin** [comment]
I'd prepare a separate PR after this if you don't mind.

On Mon, Dec 7, 2015, 23:13 Aaron Tull <notifications@github.com> wrote:

> Does anyone have any objection to creating Observable.doAfterTermination
> as an alias for finallyDo and deprecating the original finallyDo?
>
> @artem-zinnatullin <https://github.com/artem-zinnatullin> would you like
> to deprecate finallyDo -> doAfterTerminate in this PR?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxJava/pull/3434#issuecomment-162646316>.
>
-- 

@artem_zin

**Comment by stealthcode** [comment]
Rebase please so we can merge.

**Comment by artem-zinnatullin** [comment]
Rebased!

**Comment by stealthcode** [comment]
:+1:

**Comment by akarnokd** [comment]
:+1:

**Comment by stevegury** [comment]
:+1:

**Pull request merged**
